import type { Company } from "./types";

// Local fallback used when the backend API is unreachable, so the
// directory (and every company logo) always renders in the demo.
export const sampleCompanies: Company[] = [
  {
    name: "OpenAI",
    slug: "openai",
    logo_url: "https://www.google.com/s2/favicons?domain=openai.com&sz=128",
    description: "AI research and deployment company.",
    category: "Generative AI",
    stage: "Late Stage",
    headquarters: "San Francisco, USA",
    website: "https://openai.com",
    founded_year: 2015,
    employee_count: 4500,
    funding_amount: 13000000000,
    growth_score: 98,
  },
  {
    name: "Anthropic",
    slug: "anthropic",
    logo_url: "https://www.google.com/s2/favicons?domain=anthropic.com&sz=128",
    description: "AI safety and language models.",
    category: "LLM",
    stage: "Growth",
    headquarters: "San Francisco, USA",
    website: "https://anthropic.com",
    founded_year: 2021,
    employee_count: 1200,
    funding_amount: 7500000000,
    growth_score: 95,
  },
  {
    name: "Hugging Face",
    slug: "hugging-face",
    logo_url: "https://www.google.com/s2/favicons?domain=huggingface.co&sz=128",
    description: "The open-source platform for machine learning models.",
    category: "ML Platform",
    stage: "Growth",
    headquarters: "New York, USA",
    website: "https://huggingface.co",
    founded_year: 2016,
    employee_count: 350,
    funding_amount: 395000000,
    growth_score: 91,
  },
  {
    name: "Mistral AI",
    slug: "mistral-ai",
    logo_url: "https://www.google.com/s2/favicons?domain=mistral.ai&sz=128",
    description: "Open-weight frontier models built in Europe.",
    category: "LLM",
    stage: "Growth",
    headquarters: "Paris, France",
    website: "https://mistral.ai",
    founded_year: 2023,
    employee_count: 60,
    funding_amount: 1100000000,
    growth_score: 90,
  },
  {
    name: "Perplexity",
    slug: "perplexity",
    logo_url: "https://www.google.com/s2/favicons?domain=perplexity.ai&sz=128",
    description: "Conversational answer engine for the web.",
    category: "AI Search",
    stage: "Early Stage",
    headquarters: "San Francisco, USA",
    website: "https://perplexity.ai",
    founded_year: 2022,
    employee_count: 120,
    funding_amount: 165000000,
    growth_score: 89,
  },
  {
    name: "Cohere",
    slug: "cohere",
    logo_url: "https://www.google.com/s2/favicons?domain=cohere.com&sz=128",
    description: "Enterprise-grade large language models.",
    category: "LLM",
    stage: "Growth",
    headquarters: "Toronto, Canada",
    website: "https://cohere.com",
    founded_year: 2019,
    employee_count: 400,
    funding_amount: 970000000,
    growth_score: 86,
  },
  {
    name: "Stability AI",
    slug: "stability-ai",
    logo_url: "https://www.google.com/s2/favicons?domain=stability.ai&sz=128",
    description: "Open models for image, video, and audio generation.",
    category: "Generative AI",
    stage: "Growth",
    headquarters: "London, UK",
    website: "https://stability.ai",
    founded_year: 2020,
    employee_count: 200,
    funding_amount: 250000000,
    growth_score: 82,
  },
  {
    name: "Runway",
    slug: "runway",
    logo_url: "https://www.google.com/s2/favicons?domain=runwayml.com&sz=128",
    description: "Generative AI tools for video and creative work.",
    category: "Generative AI",
    stage: "Growth",
    headquarters: "New York, USA",
    website: "https://runwayml.com",
    founded_year: 2018,
    employee_count: 100,
    funding_amount: 237000000,
    growth_score: 80,
  },
];
