export interface SeedCompany {
  name: string;
  slug: string;
  logo_url: string;
  description: string;
  category: string;
  stage: string;
  hq_city: string;
  hq_country: string;
  website: string;
  founded_year: number;
  employee_count: number;
  funding_total: number;
  is_unicorn: boolean;
  valuation: number;
  growth_score: number;
  data_confidence_score: number;
  last_scraped_at: string;
}

export const companies: SeedCompany[] = [
  {
    name: "OpenAI",
    slug: "openai",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/0/04/OpenAI_Logo.svg",
    description: "AI research and deployment company creating advanced language models including GPT-4, DALL-E, and ChatGPT.",
    category: "Large Language Models",
    stage: "Late Stage",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://openai.com",
    founded_year: 2015,
    employee_count: 4500,
    funding_total: 13000000000,
    is_unicorn: true,
    valuation: 80000000000,
    growth_score: 98,
    data_confidence_score: 99,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Anthropic",
    slug: "anthropic",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Anthropic_logo.svg/128px-Anthropic_logo.svg.png",
    description: "AI safety company building reliable and steerable AI systems with the Claude language model.",
    category: "Large Language Models",
    stage: "Growth",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://anthropic.com",
    founded_year: 2021,
    employee_count: 1200,
    funding_total: 7500000000,
    is_unicorn: true,
    valuation: 18000000000,
    growth_score: 95,
    data_confidence_score: 95,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Google DeepMind",
    slug: "google-deepmind",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Google_DeepMind_logo.svg/128px-Google_DeepMind_logo.svg.png",
    description: "AI research laboratory developing general-purpose AI technologies including AlphaFold and AlphaGo.",
    category: "AI Research",
    stage: "Late Stage",
    hq_city: "London",
    hq_country: "UK",
    website: "https://deepmind.com",
    founded_year: 2010,
    employee_count: 2500,
    funding_total: 5000000000,
    is_unicorn: true,
    valuation: 50000000000,
    growth_score: 92,
    data_confidence_score: 98,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Hugging Face",
    slug: "hugging-face",
    logo_url: "https://huggingface.co/front/assets/huggingface-logo-noborder.svg",
    description: "AI community platform and model hub for machine learning models and collaborative development.",
    category: "AI Infrastructure",
    stage: "Growth",
    hq_city: "New York",
    hq_country: "USA",
    website: "https://huggingface.co",
    founded_year: 2016,
    employee_count: 500,
    funding_total: 395000000,
    is_unicorn: true,
    valuation: 4500000000,
    growth_score: 90,
    data_confidence_score: 94,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Midjourney",
    slug: "midjourney",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Midjourney_website_icon.svg/128px-Midjourney_website_icon.svg.png",
    description: "AI art and image generation platform known for high-quality creative outputs and community innovation.",
    category: "Image Generation",
    stage: "Growth",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://midjourney.com",
    founded_year: 2021,
    employee_count: 200,
    funding_total: 200000000,
    is_unicorn: true,
    valuation: 10000000000,
    growth_score: 88,
    data_confidence_score: 85,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Stability AI",
    slug: "stability-ai",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Stability_AI_logo.svg/128px-Stability_AI_logo.svg.png",
    description: "Open-source AI company behind Stable Diffusion for image generation.",
    category: "Image Generation",
    stage: "Growth",
    hq_city: "London",
    hq_country: "UK",
    website: "https://stability.ai",
    founded_year: 2020,
    employee_count: 300,
    funding_total: 101000000,
    is_unicorn: true,
    valuation: 1000000000,
    growth_score: 85,
    data_confidence_score: 80,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Cohere",
    slug: "cohere",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Cohere_logo.svg/128px-Cohere_logo.svg.png",
    description: "Enterprise AI platform providing large language models for businesses with data privacy focus.",
    category: "Large Language Models",
    stage: "Growth",
    hq_city: "Toronto",
    hq_country: "Canada",
    website: "https://cohere.com",
    founded_year: 2019,
    employee_count: 500,
    funding_total: 445000000,
    is_unicorn: true,
    valuation: 5500000000,
    growth_score: 87,
    data_confidence_score: 90,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Perplexity AI",
    slug: "perplexity-ai",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Perplexity_AI_logo.svg/128px-Perplexity_AI_logo.svg.png",
    description: "AI-powered answer engine combining LLMs with real-time web search for accurate responses.",
    category: "AI Search",
    stage: "Growth",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://perplexity.ai",
    founded_year: 2022,
    employee_count: 150,
    funding_total: 165000000,
    is_unicorn: true,
    valuation: 1000000000,
    growth_score: 93,
    data_confidence_score: 88,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Runway",
    slug: "runway",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Runway_logo.svg/128px-Runway_logo.svg.png",
    description: "AI video generation and editing platform for creators using generative AI tools.",
    category: "Video Generation",
    stage: "Growth",
    hq_city: "New York",
    hq_country: "USA",
    website: "https://runwayml.com",
    founded_year: 2018,
    employee_count: 250,
    funding_total: 237000000,
    is_unicorn: true,
    valuation: 1500000000,
    growth_score: 86,
    data_confidence_score: 85,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Synthesia",
    slug: "synthesia",
    logo_url: "",
    description: "AI video synthesis platform creating professional videos with virtual avatars from text.",
    category: "Video Generation",
    stage: "Growth",
    hq_city: "London",
    hq_country: "UK",
    website: "https://synthesia.io",
    founded_year: 2017,
    employee_count: 200,
    funding_total: 156000000,
    is_unicorn: true,
    valuation: 1000000000,
    growth_score: 84,
    data_confidence_score: 82,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Databricks",
    slug: "databricks",
    logo_url: "https://www.databricks.com/wp-content/uploads/2019/02/databricks-logo-1.png",
    description: "Data and AI platform unifying data engineering, analytics, and ML on a lakehouse architecture.",
    category: "AI Infrastructure",
    stage: "Late Stage",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://databricks.com",
    founded_year: 2013,
    employee_count: 5000,
    funding_total: 3500000000,
    is_unicorn: true,
    valuation: 43000000000,
    growth_score: 91,
    data_confidence_score: 97,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Scale AI",
    slug: "scale-ai",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Scale_AI_logo.svg/128px-Scale_AI_logo.svg.png",
    description: "Data annotation and AI infrastructure for ML pipelines serving enterprises and governments.",
    category: "AI Infrastructure",
    stage: "Late Stage",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://scale.com",
    founded_year: 2016,
    employee_count: 1000,
    funding_total: 600000000,
    is_unicorn: true,
    valuation: 7300000000,
    growth_score: 88,
    data_confidence_score: 90,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Replit",
    slug: "replit",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Replit_logo.svg/128px-Replit_logo.svg.png",
    description: "AI-powered coding platform with collaborative IDE and code generation capabilities.",
    category: "Code Generation",
    stage: "Growth",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://replit.com",
    founded_year: 2016,
    employee_count: 300,
    funding_total: 200000000,
    is_unicorn: true,
    valuation: 1200000000,
    growth_score: 89,
    data_confidence_score: 85,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Cursor",
    slug: "cursor",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Cursor_logo.svg/128px-Cursor_logo.svg.png",
    description: "AI-first code editor for pair programming with intelligent code generation.",
    category: "Code Generation",
    stage: "Early Stage",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://cursor.sh",
    founded_year: 2022,
    employee_count: 50,
    funding_total: 60000000,
    is_unicorn: false,
    valuation: 400000000,
    growth_score: 96,
    data_confidence_score: 80,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "ElevenLabs",
    slug: "elevenlabs",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/ElevenLabs_logo.svg/128px-ElevenLabs_logo.svg.png",
    description: "AI voice synthesis platform generating natural speech in multiple languages.",
    category: "Audio Generation",
    stage: "Growth",
    hq_city: "New York",
    hq_country: "USA",
    website: "https://elevenlabs.io",
    founded_year: 2022,
    employee_count: 100,
    funding_total: 19000000,
    is_unicorn: false,
    valuation: 100000000,
    growth_score: 91,
    data_confidence_score: 82,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Character AI",
    slug: "character-ai",
    logo_url: "",
    description: "AI chatbot platform for creating and interacting with AI-powered characters.",
    category: "Conversational AI",
    stage: "Growth",
    hq_city: "Palo Alto",
    hq_country: "USA",
    website: "https://character.ai",
    founded_year: 2021,
    employee_count: 150,
    funding_total: 193000000,
    is_unicorn: true,
    valuation: 1000000000,
    growth_score: 87,
    data_confidence_score: 80,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Mistral AI",
    slug: "mistral-ai",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Mistral_AI_logo.svg/128px-Mistral_AI_logo.svg.png",
    description: "French AI company building open-weight large language models with focus on efficiency.",
    category: "Large Language Models",
    stage: "Growth",
    hq_city: "Paris",
    hq_country: "France",
    website: "https://mistral.ai",
    founded_year: 2023,
    employee_count: 100,
    funding_total: 640000000,
    is_unicorn: true,
    valuation: 6000000000,
    growth_score: 92,
    data_confidence_score: 85,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Cognition AI",
    slug: "cognition-ai",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Cognition_AI_logo.svg/128px-Cognition_AI_logo.svg.png",
    description: "AI company building Devin, the first AI software engineer for autonomous software projects.",
    category: "Code Generation",
    stage: "Early Stage",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://cognition.ai",
    founded_year: 2023,
    employee_count: 30,
    funding_total: 21000000,
    is_unicorn: false,
    valuation: 200000000,
    growth_score: 97,
    data_confidence_score: 70,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Suno AI",
    slug: "suno-ai",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Suno_AI_logo.svg/128px-Suno_AI_logo.svg.png",
    description: "AI music generation platform creating original songs with lyrics and vocals from text.",
    category: "Audio Generation",
    stage: "Early Stage",
    hq_city: "Cambridge",
    hq_country: "USA",
    website: "https://suno.ai",
    founded_year: 2022,
    employee_count: 40,
    funding_total: 125000000,
    is_unicorn: false,
    valuation: 500000000,
    growth_score: 93,
    data_confidence_score: 75,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Groq",
    slug: "groq",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Groq_logo.svg/128px-Groq_logo.svg.png",
    description: "AI inference company building ultra-fast hardware for real-time AI model deployment.",
    category: "AI Infrastructure",
    stage: "Growth",
    hq_city: "Mountain View",
    hq_country: "USA",
    website: "https://groq.com",
    founded_year: 2016,
    employee_count: 200,
    funding_total: 367000000,
    is_unicorn: true,
    valuation: 1000000000,
    growth_score: 90,
    data_confidence_score: 82,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "CoreWeave",
    slug: "coreweave",
    logo_url: "",
    description: "Cloud provider specialized in GPU-accelerated workloads for AI and ML.",
    category: "AI Infrastructure",
    stage: "Growth",
    hq_city: "Roseland",
    hq_country: "USA",
    website: "https://coreweave.com",
    founded_year: 2017,
    employee_count: 300,
    funding_total: 500000000,
    is_unicorn: true,
    valuation: 2000000000,
    growth_score: 89,
    data_confidence_score: 82,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Anduril",
    slug: "anduril",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Anduril_logo.svg/128px-Anduril_logo.svg.png",
    description: "AI defense technology building autonomous systems for military and security.",
    category: "Defense AI",
    stage: "Late Stage",
    hq_city: "Irvine",
    hq_country: "USA",
    website: "https://anduril.com",
    founded_year: 2017,
    employee_count: 2000,
    funding_total: 2800000000,
    is_unicorn: true,
    valuation: 14000000000,
    growth_score: 90,
    data_confidence_score: 88,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Figure AI",
    slug: "figure-ai",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Figure_AI_logo.svg/128px-Figure_AI_logo.svg.png",
    description: "AI robotics company building general-purpose humanoid robots for labor automation.",
    category: "Robotics AI",
    stage: "Growth",
    hq_city: "Sunnyvale",
    hq_country: "USA",
    website: "https://figure.ai",
    founded_year: 2022,
    employee_count: 100,
    funding_total: 754000000,
    is_unicorn: true,
    valuation: 2600000000,
    growth_score: 94,
    data_confidence_score: 75,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Harvey AI",
    slug: "harvey-ai",
    logo_url: "",
    description: "AI platform for legal professionals providing document analysis and legal research automation.",
    category: "Legal AI",
    stage: "Growth",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://harvey.ai",
    founded_year: 2022,
    employee_count: 80,
    funding_total: 106000000,
    is_unicorn: false,
    valuation: 700000000,
    growth_score: 88,
    data_confidence_score: 78,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "HeyGen",
    slug: "heygen",
    logo_url: "",
    description: "AI video generation platform for professional videos with AI avatars.",
    category: "Video Generation",
    stage: "Growth",
    hq_city: "Los Angeles",
    hq_country: "USA",
    website: "https://heygen.com",
    founded_year: 2020,
    employee_count: 100,
    funding_total: 60000000,
    is_unicorn: false,
    valuation: 500000000,
    growth_score: 88,
    data_confidence_score: 78,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "LangChain",
    slug: "langchain",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/LangChain_logo.svg/128px-LangChain_logo.svg.png",
    description: "Framework for building LLM-powered applications with composable chains and agents.",
    category: "AI Infrastructure",
    stage: "Early Stage",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://langchain.com",
    founded_year: 2022,
    employee_count: 60,
    funding_total: 35000000,
    is_unicorn: false,
    valuation: 200000000,
    growth_score: 92,
    data_confidence_score: 78,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Pinecone",
    slug: "pinecone",
    logo_url: "",
    description: "Vector database platform for building AI applications with semantic search.",
    category: "AI Infrastructure",
    stage: "Growth",
    hq_city: "New York",
    hq_country: "USA",
    website: "https://pinecone.io",
    founded_year: 2019,
    employee_count: 200,
    funding_total: 138000000,
    is_unicorn: true,
    valuation: 1000000000,
    growth_score: 85,
    data_confidence_score: 85,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Skild AI",
    slug: "skild-ai",
    logo_url: "",
    description: "AI robotics company building foundation models for general-purpose robot intelligence.",
    category: "Robotics AI",
    stage: "Early Stage",
    hq_city: "Pittsburgh",
    hq_country: "USA",
    website: "https://skild.ai",
    founded_year: 2023,
    employee_count: 30,
    funding_total: 300000000,
    is_unicorn: true,
    valuation: 1500000000,
    growth_score: 91,
    data_confidence_score: 65,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Fireworks AI",
    slug: "fireworks-ai",
    logo_url: "",
    description: "AI inference platform for fast deployment of open-source and custom language models.",
    category: "AI Infrastructure",
    stage: "Early Stage",
    hq_city: "Mountain View",
    hq_country: "USA",
    website: "https://fireworks.ai",
    founded_year: 2022,
    employee_count: 60,
    funding_total: 55000000,
    is_unicorn: false,
    valuation: 300000000,
    growth_score: 85,
    data_confidence_score: 75,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Abridge",
    slug: "abridge",
    logo_url: "",
    description: "AI medical documentation generating clinical notes from patient conversations.",
    category: "Healthcare AI",
    stage: "Growth",
    hq_city: "Pittsburgh",
    hq_country: "USA",
    website: "https://abridge.com",
    founded_year: 2018,
    employee_count: 200,
    funding_total: 212000000,
    is_unicorn: true,
    valuation: 1000000000,
    growth_score: 87,
    data_confidence_score: 80,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Insitro",
    slug: "insitro",
    logo_url: "",
    description: "AI-driven drug discovery using machine learning to identify therapeutic candidates.",
    category: "Healthcare AI",
    stage: "Growth",
    hq_city: "South San Francisco",
    hq_country: "USA",
    website: "https://insitro.com",
    founded_year: 2018,
    employee_count: 200,
    funding_total: 643000000,
    is_unicorn: true,
    valuation: 3000000000,
    growth_score: 81,
    data_confidence_score: 82,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Helsing",
    slug: "helsing",
    logo_url: "",
    description: "European AI defense company building AI software for military decision-making.",
    category: "Defense AI",
    stage: "Growth",
    hq_city: "Munich",
    hq_country: "Germany",
    website: "https://helsing.ai",
    founded_year: 2021,
    employee_count: 200,
    funding_total: 300000000,
    is_unicorn: true,
    valuation: 5000000000,
    growth_score: 88,
    data_confidence_score: 78,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Shield AI",
    slug: "shield-ai",
    logo_url: "",
    description: "AI defense technology building autonomous systems for military and aerospace.",
    category: "Defense AI",
    stage: "Growth",
    hq_city: "San Diego",
    hq_country: "USA",
    website: "https://shield.ai",
    founded_year: 2015,
    employee_count: 500,
    funding_total: 500000000,
    is_unicorn: true,
    valuation: 2800000000,
    growth_score: 86,
    data_confidence_score: 82,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Together AI",
    slug: "together-ai",
    logo_url: "",
    description: "Cloud platform for training and running open-source AI models with optimized inference.",
    category: "AI Infrastructure",
    stage: "Growth",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://together.ai",
    founded_year: 2022,
    employee_count: 80,
    funding_total: 130000000,
    is_unicorn: false,
    valuation: 700000000,
    growth_score: 86,
    data_confidence_score: 78,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Weights & Biases",
    slug: "weights-biases",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Weights_%26_Biases_logo.svg/128px-Weights_%26_Biases_logo.svg.png",
    description: "MLOps platform for experiment tracking, model management, and ML collaboration.",
    category: "AI Infrastructure",
    stage: "Growth",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://wandb.ai",
    founded_year: 2017,
    employee_count: 300,
    funding_total: 250000000,
    is_unicorn: true,
    valuation: 1000000000,
    growth_score: 81,
    data_confidence_score: 85,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Covariant",
    slug: "covariant",
    logo_url: "",
    description: "AI robotics company building universal AI for robots in warehouse logistics.",
    category: "Robotics AI",
    stage: "Growth",
    hq_city: "Berkeley",
    hq_country: "USA",
    website: "https://covariant.ai",
    founded_year: 2017,
    employee_count: 200,
    funding_total: 245000000,
    is_unicorn: true,
    valuation: 1000000000,
    growth_score: 82,
    data_confidence_score: 82,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Sierra AI",
    slug: "sierra-ai",
    logo_url: "",
    description: "Conversational AI platform for enterprises building customer-facing AI agents.",
    category: "Conversational AI",
    stage: "Growth",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://sierra.ai",
    founded_year: 2022,
    employee_count: 80,
    funding_total: 110000000,
    is_unicorn: false,
    valuation: 500000000,
    growth_score: 85,
    data_confidence_score: 72,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Adept AI",
    slug: "adept-ai",
    logo_url: "",
    description: "AI research building general intelligence that can use software tools and automate workflows.",
    category: "AI Agents",
    stage: "Growth",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://adept.ai",
    founded_year: 2022,
    employee_count: 80,
    funding_total: 350000000,
    is_unicorn: true,
    valuation: 1000000000,
    growth_score: 83,
    data_confidence_score: 78,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Inflection AI",
    slug: "inflection-ai",
    logo_url: "",
    description: "AI company building personal AI assistants with emotional intelligence.",
    category: "Conversational AI",
    stage: "Growth",
    hq_city: "Palo Alto",
    hq_country: "USA",
    website: "https://inflection.ai",
    founded_year: 2022,
    employee_count: 100,
    funding_total: 1300000000,
    is_unicorn: true,
    valuation: 4000000000,
    growth_score: 85,
    data_confidence_score: 82,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Pika Labs",
    slug: "pika-labs",
    logo_url: "",
    description: "AI video generation platform creating high-quality videos from text prompts.",
    category: "Video Generation",
    stage: "Early Stage",
    hq_city: "Palo Alto",
    hq_country: "USA",
    website: "https://pika.art",
    founded_year: 2023,
    employee_count: 30,
    funding_total: 55000000,
    is_unicorn: false,
    valuation: 250000000,
    growth_score: 90,
    data_confidence_score: 75,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Luma AI",
    slug: "luma-ai",
    logo_url: "",
    description: "AI 3D content creation generating realistic 3D models and scenes from text and images.",
    category: "3D Generation",
    stage: "Early Stage",
    hq_city: "Palo Alto",
    hq_country: "USA",
    website: "https://lumalabs.ai",
    founded_year: 2021,
    employee_count: 40,
    funding_total: 43000000,
    is_unicorn: false,
    valuation: 200000000,
    growth_score: 86,
    data_confidence_score: 72,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Poolside",
    slug: "poolside",
    logo_url: "",
    description: "AI company building foundation models for software development and code generation.",
    category: "Code Generation",
    stage: "Early Stage",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://poolside.ai",
    founded_year: 2023,
    employee_count: 40,
    funding_total: 126000000,
    is_unicorn: false,
    valuation: 500000000,
    growth_score: 81,
    data_confidence_score: 70,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Modal",
    slug: "modal",
    logo_url: "",
    description: "Cloud platform for AI and ML workloads with serverless GPU compute.",
    category: "AI Infrastructure",
    stage: "Early Stage",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://modal.com",
    founded_year: 2021,
    employee_count: 50,
    funding_total: 25000000,
    is_unicorn: false,
    valuation: 150000000,
    growth_score: 87,
    data_confidence_score: 75,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Notion AI",
    slug: "notion-ai",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Notion_logo.svg/128px-Notion_logo.svg.png",
    description: "AI-powered workspace with writing assistance and project collaboration.",
    category: "Productivity",
    stage: "Late Stage",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://notion.so",
    founded_year: 2013,
    employee_count: 800,
    funding_total: 275000000,
    is_unicorn: true,
    valuation: 10000000000,
    growth_score: 83,
    data_confidence_score: 90,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Jasper AI",
    slug: "jasper-ai",
    logo_url: "",
    description: "AI content creation platform for marketing teams.",
    category: "Content Generation",
    stage: "Growth",
    hq_city: "Austin",
    hq_country: "USA",
    website: "https://jasper.ai",
    founded_year: 2021,
    employee_count: 400,
    funding_total: 131000000,
    is_unicorn: true,
    valuation: 1700000000,
    growth_score: 80,
    data_confidence_score: 82,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "AI21 Labs",
    slug: "ai21-labs",
    logo_url: "",
    description: "AI research lab building LLMs and writing assistants with Jurassic-2 models.",
    category: "Large Language Models",
    stage: "Growth",
    hq_city: "Tel Aviv",
    hq_country: "Israel",
    website: "https://ai21.com",
    founded_year: 2020,
    employee_count: 300,
    funding_total: 336000000,
    is_unicorn: true,
    valuation: 1400000000,
    growth_score: 82,
    data_confidence_score: 85,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Glean",
    slug: "glean",
    logo_url: "",
    description: "AI-powered enterprise search connecting all company applications.",
    category: "AI Search",
    stage: "Growth",
    hq_city: "Palo Alto",
    hq_country: "USA",
    website: "https://glean.com",
    founded_year: 2019,
    employee_count: 500,
    funding_total: 355000000,
    is_unicorn: true,
    valuation: 2200000000,
    growth_score: 86,
    data_confidence_score: 88,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "DataRobot",
    slug: "datarobot",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/DataRobot_logo.svg/128px-DataRobot_logo.svg.png",
    description: "Automated machine learning platform for enterprise AI development.",
    category: "AI Infrastructure",
    stage: "Late Stage",
    hq_city: "Boston",
    hq_country: "USA",
    website: "https://datarobot.com",
    founded_year: 2012,
    employee_count: 1200,
    funding_total: 1000000000,
    is_unicorn: true,
    valuation: 6300000000,
    growth_score: 75,
    data_confidence_score: 85,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Dataiku",
    slug: "dataiku",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Dataiku_logo.svg/128px-Dataiku_logo.svg.png",
    description: "Enterprise AI platform for building and deploying AI applications at scale.",
    category: "AI Infrastructure",
    stage: "Growth",
    hq_city: "New York",
    hq_country: "USA",
    website: "https://dataiku.com",
    founded_year: 2013,
    employee_count: 1000,
    funding_total: 446000000,
    is_unicorn: true,
    valuation: 3700000000,
    growth_score: 78,
    data_confidence_score: 85,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Descript",
    slug: "descript",
    logo_url: "",
    description: "AI-powered video and audio editing platform.",
    category: "Video Generation",
    stage: "Growth",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://descript.com",
    founded_year: 2017,
    employee_count: 200,
    funding_total: 100000000,
    is_unicorn: false,
    valuation: 500000000,
    growth_score: 78,
    data_confidence_score: 82,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "AssemblyAI",
    slug: "assemblyai",
    logo_url: "",
    description: "AI speech recognition and audio intelligence API.",
    category: "Audio Generation",
    stage: "Growth",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://assemblyai.com",
    founded_year: 2017,
    employee_count: 100,
    funding_total: 115000000,
    is_unicorn: false,
    valuation: 500000000,
    growth_score: 80,
    data_confidence_score: 82,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Deepgram",
    slug: "deepgram",
    logo_url: "",
    description: "AI speech recognition platform for real-time transcription and voice AI.",
    category: "Audio Generation",
    stage: "Growth",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://deepgram.com",
    founded_year: 2015,
    employee_count: 200,
    funding_total: 250000000,
    is_unicorn: false,
    valuation: 500000000,
    growth_score: 79,
    data_confidence_score: 82,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Zipline",
    slug: "zipline",
    logo_url: "",
    description: "AI-powered autonomous drone delivery for medical supplies and logistics.",
    category: "Robotics AI",
    stage: "Late Stage",
    hq_city: "South San Francisco",
    hq_country: "USA",
    website: "https://flyzipline.com",
    founded_year: 2014,
    employee_count: 1000,
    funding_total: 500000000,
    is_unicorn: true,
    valuation: 4200000000,
    growth_score: 85,
    data_confidence_score: 88,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Waabi",
    slug: "waabi",
    logo_url: "",
    description: "Autonomous driving technology for AI-first self-driving freight systems.",
    category: "Robotics AI",
    stage: "Growth",
    hq_city: "Toronto",
    hq_country: "Canada",
    website: "https://waabi.ai",
    founded_year: 2021,
    employee_count: 100,
    funding_total: 135000000,
    is_unicorn: false,
    valuation: 500000000,
    growth_score: 83,
    data_confidence_score: 75,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "SambaNova",
    slug: "sambanova",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/SambaNova_logo.svg/128px-SambaNova_logo.svg.png",
    description: "AI hardware and software platform for training and running large AI models.",
    category: "AI Infrastructure",
    stage: "Late Stage",
    hq_city: "Palo Alto",
    hq_country: "USA",
    website: "https://sambanova.ai",
    founded_year: 2017,
    employee_count: 800,
    funding_total: 1100000000,
    is_unicorn: true,
    valuation: 5000000000,
    growth_score: 78,
    data_confidence_score: 85,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Cerebras",
    slug: "cerebras",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Cerebras_Logo.svg/128px-Cerebras_Logo.svg.png",
    description: "AI hardware company building the world's largest computer chip for deep learning.",
    category: "AI Infrastructure",
    stage: "Late Stage",
    hq_city: "Sunnyvale",
    hq_country: "USA",
    website: "https://cerebras.net",
    founded_year: 2015,
    employee_count: 500,
    funding_total: 750000000,
    is_unicorn: true,
    valuation: 4000000000,
    growth_score: 80,
    data_confidence_score: 85,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Vercel",
    slug: "vercel",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Vercel_logo.svg/128px-Vercel_logo.svg.png",
    description: "Cloud platform for frontend developers with serverless deployment and edge functions.",
    category: "AI Infrastructure",
    stage: "Growth",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://vercel.com",
    founded_year: 2015,
    employee_count: 500,
    funding_total: 250000000,
    is_unicorn: true,
    valuation: 3000000000,
    growth_score: 85,
    data_confidence_score: 90,
    last_scraped_at: new Date().toISOString(),
  },
  {
    name: "Replicate",
    slug: "replicate",
    logo_url: "",
    description: "Cloud platform for running and deploying ML models with community library.",
    category: "AI Infrastructure",
    stage: "Early Stage",
    hq_city: "San Francisco",
    hq_country: "USA",
    website: "https://replicate.com",
    founded_year: 2019,
    employee_count: 40,
    funding_total: 55000000,
    is_unicorn: false,
    valuation: 300000000,
    growth_score: 84,
    data_confidence_score: 78,
    last_scraped_at: new Date().toISOString(),
  },
];