export interface SeedInvestor {
  name: string;
  slug: string;
  type: "VC" | "Angel" | "Corporate";
  bio: string;
  aum: number;
  portfolio_count: number;
  stage_focus: string[];
  sector_focus: string[];
  location: string;
  logo_url: string;
  avg_check_size: number;
  fund_number: number;
}

export const investors: SeedInvestor[] = [
  {
    name: "Sequoia Capital",
    slug: "sequoia-capital",
    type: "VC",
    bio: "Backing the daring from idea to iconic. Sequoia partners with visionary founders building category-defining companies.",
    aum: 85000000000,
    portfolio_count: 1500,
    stage_focus: ["Seed", "Series A", "Series B", "Growth"],
    sector_focus: ["AI Infrastructure", "AI Agents", "Enterprise AI", "Developer Tools", "Healthcare AI"],
    location: "Menlo Park, California, USA",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Sequoia_Capital_logo.svg/128px-Sequoia_Capital_logo.svg.png",
    avg_check_size: 15000000,
    fund_number: 12,
  },
  {
    name: "Andreessen Horowitz (a16z)",
    slug: "a16z",
    type: "VC",
    bio: "Software eats the world. a16z invests in the boldest entrepreneurs building the future.",
    aum: 35000000000,
    portfolio_count: 800,
    stage_focus: ["Seed", "Series A", "Growth"],
    sector_focus: ["AI Agents", "AI Infrastructure", "Consumer AI", "Crypto", "Gaming"],
    location: "Menlo Park, California, USA",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Andreessen_Horowitz_logo.svg/128px-Andreessen_Horowitz_logo.svg.png",
    avg_check_size: 20000000,
    fund_number: 8,
  },
  {
    name: "Lightspeed Venture Partners",
    slug: "lightspeed",
    type: "VC",
    bio: "Lightspeed invests in early-stage technology companies across enterprise, consumer, and fintech sectors.",
    aum: 18000000000,
    portfolio_count: 600,
    stage_focus: ["Seed", "Series A", "Series B"],
    sector_focus: ["Enterprise AI", "AI Infrastructure", "Fintech AI", "Consumer AI"],
    location: "Menlo Park, California, USA",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Lightspeed_Venture_Partners_logo.svg/128px-Lightspeed_Venture_Partners_logo.svg.png",
    avg_check_size: 12000000,
    fund_number: 15,
  },
  {
    name: "Khosla Ventures",
    slug: "khosla-ventures",
    type: "VC",
    bio: "Khosla Ventures focuses on early-stage companies in technology, healthcare, and sustainability sectors.",
    aum: 15000000000,
    portfolio_count: 400,
    stage_focus: ["Seed", "Series A"],
    sector_focus: ["AI Agents", "Healthcare AI", "Climate AI", "Robotics AI"],
    location: "Menlo Park, California, USA",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Khosla_Ventures_logo.svg/128px-Khosla_Ventures_logo.svg.png",
    avg_check_size: 10000000,
    fund_number: 10,
  },
  {
    name: "Accel",
    slug: "accel",
    type: "VC",
    bio: "Accel invests in people and their companies from the earliest stages through all phases of growth.",
    aum: 20000000000,
    portfolio_count: 700,
    stage_focus: ["Seed", "Series A", "Growth"],
    sector_focus: ["Enterprise AI", "AI Infrastructure", "Developer Tools", "SaaS"],
    location: "Palo Alto, California, USA",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Accel_logo.svg/128px-Accel_logo.svg.png",
    avg_check_size: 15000000,
    fund_number: 14,
  },
  {
    name: "Index Ventures",
    slug: "index-ventures",
    type: "VC",
    bio: "Index Ventures backs the best founders across seed, growth, and public markets globally.",
    aum: 16000000000,
    portfolio_count: 500,
    stage_focus: ["Seed", "Series A", "Growth"],
    sector_focus: ["AI Infrastructure", "Consumer AI", "Fintech AI", "Enterprise AI"],
    location: "San Francisco, California, USA",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Index_Ventures_logo.svg/128px-Index_Ventures_logo.svg.png",
    avg_check_size: 12000000,
    fund_number: 12,
  },
  {
    name: "NEA",
    slug: "nea",
    type: "VC",
    bio: "New Enterprise Associates invests in technology and healthcare companies at all stages.",
    aum: 25000000000,
    portfolio_count: 900,
    stage_focus: ["Series A", "Series B", "Growth"],
    sector_focus: ["Healthcare AI", "Enterprise AI", "AI Infrastructure", "Biotech"],
    location: "Menlo Park, California, USA",
    logo_url: "",
    avg_check_size: 18000000,
    fund_number: 20,
  },
  {
    name: "Bessemer Venture Partners",
    slug: "bvp",
    type: "VC",
    bio: "Bessemer invests in early-stage and growth companies across cloud, consumer, and healthcare.",
    aum: 18000000000,
    portfolio_count: 600,
    stage_focus: ["Seed", "Series A", "Growth"],
    sector_focus: ["Cloud AI", "Enterprise AI", "Consumer AI", "Healthcare AI"],
    location: "Menlo Park, California, USA",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Bessemer_Venture_Partners_logo.svg/128px-Bessemer_Venture_Partners_logo.svg.png",
    avg_check_size: 14000000,
    fund_number: 18,
  },
  {
    name: "Founders Fund",
    slug: "founders-fund",
    type: "VC",
    bio: "Founders Fund invests in companies building revolutionary technologies of the future.",
    aum: 12000000000,
    portfolio_count: 300,
    stage_focus: ["Seed", "Series A"],
    sector_focus: ["AI Agents", "Robotics AI", "Space AI", "Defense AI"],
    location: "San Francisco, California, USA",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Founders_Fund_logo.svg/128px-Founders_Fund_logo.svg.png",
    avg_check_size: 20000000,
    fund_number: 8,
  },
  {
    name: "Greylock",
    slug: "greylock",
    type: "VC",
    bio: "Greylock invests in founders building category-defining companies in consumer and enterprise.",
    aum: 10000000000,
    portfolio_count: 350,
    stage_focus: ["Seed", "Series A", "Series B"],
    sector_focus: ["Consumer AI", "Enterprise AI", "AI Infrastructure", "Developer Tools"],
    location: "Menlo Park, California, USA",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Greylock_Partners_logo.svg/128px-Greylock_Partners_logo.svg.png",
    avg_check_size: 15000000,
    fund_number: 16,
  },
  {
    name: "General Catalyst",
    slug: "general-catalyst",
    type: "VC",
    bio: "General Catalyst invests in entrepreneurs building transformational companies.",
    aum: 25000000000,
    portfolio_count: 500,
    stage_focus: ["Series A", "Series B", "Growth"],
    sector_focus: ["Enterprise AI", "AI Infrastructure", "Fintech AI", "Healthcare AI"],
    location: "Cambridge, Massachusetts, USA",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/General_Catalyst_logo.svg/128px-General_Catalyst_logo.svg.png",
    avg_check_size: 20000000,
    fund_number: 12,
  },
  {
    name: "Benchmark",
    slug: "benchmark",
    type: "VC",
    bio: "Benchmark partners with exceptional founders to build enduring companies.",
    aum: 8000000000,
    portfolio_count: 200,
    stage_focus: ["Seed", "Series A"],
    sector_focus: ["Consumer AI", "Enterprise AI", "Marketplaces", "SaaS"],
    location: "San Francisco, California, USA",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Benchmark_logo.svg/128px-Benchmark_logo.svg.png",
    avg_check_size: 25000000,
    fund_number: 10,
  },
  {
    name: "Battery Ventures",
    slug: "battery-ventures",
    type: "VC",
    bio: "Battery invests in technology companies across stages and sectors globally.",
    aum: 13000000000,
    portfolio_count: 450,
    stage_focus: ["Series A", "Series B", "Growth"],
    sector_focus: ["Enterprise AI", "AI Infrastructure", "Application Software", "Infrastructure"],
    location: "Menlo Park, California, USA",
    logo_url: "",
    avg_check_size: 15000000,
    fund_number: 14,
  },
  {
    name: "Insight Partners",
    slug: "insight-partners",
    type: "VC",
    bio: "Insight Partners invests in high-growth technology and software companies.",
    aum: 30000000000,
    portfolio_count: 400,
    stage_focus: ["Growth", "Late Stage"],
    sector_focus: ["Enterprise AI", "AI Infrastructure", "Software", "Cybersecurity"],
    location: "New York, New York, USA",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Insight_Partners_logo.svg/128px-Insight_Partners_logo.svg.png",
    avg_check_size: 50000000,
    fund_number: 12,
  },
  {
    name: "Thrive Capital",
    slug: "thrive-capital",
    type: "VC",
    bio: "Thrive Capital invests in internet and software companies across stages.",
    aum: 15000000000,
    portfolio_count: 200,
    stage_focus: ["Series A", "Series B", "Growth"],
    sector_focus: ["Consumer AI", "Enterprise AI", "Fintech AI", "Marketplaces"],
    location: "New York, New York, USA",
    logo_url: "",
    avg_check_size: 30000000,
    fund_number: 8,
  },
  {
    name: "Y Combinator",
    slug: "y-combinator",
    type: "VC",
    bio: "Y Combinator is a startup accelerator providing seed funding and mentorship.",
    aum: 5000000000,
    portfolio_count: 4000,
    stage_focus: ["Seed"],
    sector_focus: ["AI Agents", "AI Infrastructure", "Consumer AI", "Enterprise AI", "Developer Tools"],
    location: "San Francisco, California, USA",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Y_Combinator_logo.svg/128px-Y_Combinator_logo.svg.png",
    avg_check_size: 500000,
    fund_number: 35,
  },
  {
    name: "GV (Google Ventures)",
    slug: "gv",
    type: "Corporate",
    bio: "GV invests in bold founders building transformative companies.",
    aum: 8000000000,
    portfolio_count: 300,
    stage_focus: ["Seed", "Series A", "Growth"],
    sector_focus: ["AI Infrastructure", "Healthcare AI", "Enterprise AI", "Life Sciences"],
    location: "San Francisco, California, USA",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Google_Ventures_logo.svg/128px-Google_Ventures_logo.svg.png",
    avg_check_size: 20000000,
    fund_number: 8,
  },
  {
    name: "Microsoft Ventures",
    slug: "microsoft-ventures",
    type: "Corporate",
    bio: "Microsoft Ventures invests in AI, cloud, and enterprise software companies.",
    aum: 10000000000,
    portfolio_count: 250,
    stage_focus: ["Series A", "Series B", "Growth"],
    sector_focus: ["AI Infrastructure", "Enterprise AI", "Cloud AI", "Developer Tools"],
    location: "Redmond, Washington, USA",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/128px-Microsoft_logo.svg.png",
    avg_check_size: 25000000,
    fund_number: 6,
  },
  {
    name: "Salesforce Ventures",
    slug: "salesforce-ventures",
    type: "Corporate",
    bio: "Salesforce Ventures invests in enterprise software and AI companies.",
    aum: 5000000000,
    portfolio_count: 200,
    stage_focus: ["Series A", "Series B", "Growth"],
    sector_focus: ["Enterprise AI", "AI Infrastructure", "CRM AI", "SaaS"],
    location: "San Francisco, California, USA",
    logo_url: "",
    avg_check_size: 15000000,
    fund_number: 8,
  },
  {
    name: "Nat Friedman",
    slug: "nat-friedman",
    type: "Angel",
    bio: "Former GitHub CEO investing in AI infrastructure and developer tools.",
    aum: 500000000,
    portfolio_count: 50,
    stage_focus: ["Seed", "Series A"],
    sector_focus: ["AI Infrastructure", "Developer Tools", "Open Source"],
    location: "San Francisco, California, USA",
    logo_url: "",
    avg_check_size: 1000000,
    fund_number: 1,
  },
  {
    name: "Elad Gil",
    slug: "elad-gil",
    type: "Angel",
    bio: "Angel investor and former Google executive investing in AI and biotech.",
    aum: 300000000,
    portfolio_count: 80,
    stage_focus: ["Seed", "Series A"],
    sector_focus: ["AI Agents", "AI Infrastructure", "Biotech AI"],
    location: "San Francisco, California, USA",
    logo_url: "",
    avg_check_size: 750000,
    fund_number: 1,
  },
  {
    name: "Daniel Gross",
    slug: "daniel-gross",
    type: "Angel",
    bio: "Former Apple and Google AI lead investing in AI infrastructure and agents.",
    aum: 200000000,
    portfolio_count: 40,
    stage_focus: ["Seed"],
    sector_focus: ["AI Infrastructure", "AI Agents", "Developer Tools"],
    location: "San Francisco, California, USA",
    logo_url: "",
    avg_check_size: 500000,
    fund_number: 1,
  },
];
