export interface SeedNews {
  title: string;
  url: string;
  published_at: string;
  source: string;
  tag: string;
  related_company_ids: string[];
  summary: string;
}

export const news: SeedNews[] = [
  {
    title: "OpenAI Announces GPT-5 with Enhanced Reasoning Capabilities",
    url: "https://techcrunch.com/2024/06/15/openai-gpt5",
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "LLM",
    related_company_ids: [],
    summary: "OpenAI has unveiled GPT-5, featuring significantly improved reasoning, multimodal understanding, and reduced hallucinations compared to previous models.",
  },
  {
    title: "Anthropic Raises $2B in Series D Funding",
    url: "https://reuters.com/2024/06/14/anthropic-funding",
    published_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Reuters",
    tag: "Funding",
    related_company_ids: [],
    summary: "Anthropic secured $2 billion in Series D funding led by Google and Spark Capital, valuing the AI safety company at $18 billion.",
  },
  {
    title: "Mistral AI Releases Open-Weight Model with 70B Parameters",
    url: "https://theverge.com/2024/06/13/mistral-70b",
    published_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    source: "The Verge",
    tag: "Open Source",
    related_company_ids: [],
    summary: "French AI company Mistral AI released its largest open-weight model yet, featuring 70 billion parameters and competitive performance.",
  },
  {
    title: "Perplexity AI Launches Enterprise Search Platform",
    url: "https://wired.com/2024/06/12/perplexity-enterprise",
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Wired",
    tag: "Enterprise",
    related_company_ids: [],
    summary: "Perplexity AI introduced an enterprise-focused version of its AI-powered search engine with enhanced security and integration capabilities.",
  },
  {
    title: "Figure AI Demonstrates Humanoid Robot Performing Complex Tasks",
    url: "https://ieee.org/2024/06/11/figure-robot",
    published_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    source: "IEEE Spectrum",
    tag: "Robotics",
    related_company_ids: [],
    summary: "Figure AI showcased its humanoid robot successfully performing complex manipulation tasks in a factory environment.",
  },
  {
    title: "ElevenLabs Achieves $100M Valuation After Series B",
    url: "https://venturebeat.com/2024/06/10/elevenlabs",
    published_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    source: "VentureBeat",
    tag: "Funding",
    related_company_ids: [],
    summary: "AI voice synthesis startup ElevenLabs reached a $100 million valuation following a successful Series B funding round.",
  },
  {
    title: "Runway ML Introduces Real-Time Video Generation",
    url: "https://arstechnica.com/2024/06/09/runway-realtime",
    published_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Ars Technica",
    tag: "Video AI",
    related_company_ids: [],
    summary: "Runway ML announced real-time video generation capabilities, allowing creators to generate video content instantly from text prompts.",
  },
  {
    title: "Hugging Face Acquires AI Startup Argilla",
    url: "https://techcrunch.com/2024/06/08/huggingface-argilla",
    published_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "M&A",
    related_company_ids: [],
    summary: "Hugging Face acquired Argilla, a data labeling platform for AI models, to strengthen its open-source AI ecosystem.",
  },
  {
    title: "Cursor AI Raises $60M to Build AI-Powered IDE",
    url: "https://information.com/2024/06/07/cursor-funding",
    published_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    source: "The Information",
    tag: "Funding",
    related_company_ids: [],
    summary: "Cursor AI secured $60 million in funding to develop its AI-first code editor with intelligent pair programming features.",
  },
  {
    title: "Stability AI Releases Stable Diffusion 3 with Improved Quality",
    url: "https://engadget.com/2024/06/06/stable-diffusion-3",
    published_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Engadget",
    tag: "Image AI",
    related_company_ids: [],
    summary: "Stability AI launched Stable Diffusion 3, featuring significant improvements in image quality, text rendering, and prompt adherence.",
  },
  {
    title: "Cognition AI's Devin Completes First Autonomous Software Project",
    url: "https://wired.com/2024/06/05/cognition-devin",
    published_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Wired",
    tag: "AI Agents",
    related_company_ids: [],
    summary: "Cognition AI's AI software engineer Devin successfully completed its first fully autonomous software development project.",
  },
  {
    title: "Databricks Launches AI Governance Platform",
    url: "https://zdnet.com/2024/06/04/databricks-governance",
    published_at: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    source: "ZDNet",
    tag: "Enterprise",
    related_company_ids: [],
    summary: "Databricks introduced a comprehensive AI governance platform to help enterprises manage and monitor their AI deployments.",
  },
  {
    title: "Scale AI Expands into Healthcare Data Annotation",
    url: "https://forbes.com/2024/06/03/scale-healthcare",
    published_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Forbes",
    tag: "Healthcare",
    related_company_ids: [],
    summary: "Scale AI announced expansion into healthcare data annotation, providing specialized services for medical AI applications.",
  },
  {
    title: "Replit Adds Advanced AI Code Completion Features",
    url: "https://techcrunch.com/2024/06/02/replit-ai",
    published_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "Code AI",
    related_company_ids: [],
    summary: "Replit enhanced its AI-powered coding platform with advanced code completion and refactoring capabilities.",
  },
  {
    title: "Character AI Reaches 20 Million Monthly Active Users",
    url: "https://bloomberg.com/2024/06/01/character-ai-mau",
    published_at: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Bloomberg",
    tag: "Consumer",
    related_company_ids: [],
    summary: "Character AI achieved a milestone of 20 million monthly active users, solidifying its position in the AI chatbot market.",
  },
  {
    title: "Suno AI Launches AI Music Generation Marketplace",
    url: "https://rollingstone.com/2024/05/31/suno-marketplace",
    published_at: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Rolling Stone",
    tag: "Audio AI",
    related_company_ids: [],
    summary: "Suno AI introduced a marketplace for AI-generated music, allowing creators to monetize their AI compositions.",
  },
  {
    title: "Groq Unveils Ultra-Fast AI Inference Chip",
    url: "https://anandtech.com/2024/05/30/groq-chip",
    published_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    source: "AnandTech",
    tag: "Hardware",
    related_company_ids: [],
    summary: "Groq announced its new AI inference chip, claiming industry-leading performance for real-time AI applications.",
  },
  {
    title: "CoreWeave Raises $2B for GPU Cloud Expansion",
    url: "https://reuters.com/2024/05/29/coreweave-funding",
    published_at: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Reuters",
    tag: "Funding",
    related_company_ids: [],
    summary: "GPU cloud provider CoreWeave secured $2 billion in funding to expand its AI infrastructure capabilities.",
  },
  {
    title: "Anduril Wins Major Defense Contract for AI Systems",
    url: "https://defense.gov/2024/05/28/anduril-contract",
    published_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Defense News",
    tag: "Defense",
    related_company_ids: [],
    summary: "Anduril Industries secured a major defense contract to supply AI-powered autonomous systems for military applications.",
  },
  {
    title: "Harvey AI Partners with Major Law Firms",
    url: "https://law.com/2024/05/27/harvey-partners",
    published_at: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Law.com",
    tag: "Legal AI",
    related_company_ids: [],
    summary: "Harvey AI announced partnerships with several major law firms to deploy its AI-powered legal research platform.",
  },
  {
    title: "HeyGen Achieves $500M Valuation in Series B",
    url: "https://techcrunch.com/2024/05/26/heygen-funding",
    published_at: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "Funding",
    related_company_ids: [],
    summary: "AI video generation platform HeyGen reached a $500 million valuation following a successful Series B round.",
  },
  {
    title: "LangChain Integrates with Major Cloud Providers",
    url: "https://infoworld.com/2024/05/25/langchain-cloud",
    published_at: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
    source: "InfoWorld",
    tag: "Infrastructure",
    related_company_ids: [],
    summary: "LangChain announced integrations with AWS, Google Cloud, and Azure to simplify LLM application deployment.",
  },
  {
    title: "Pinecone Launches Serverless Vector Database",
    url: "https://venturebeat.com/2024/05/24/pinecone-serverless",
    published_at: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
    source: "VentureBeat",
    tag: "Infrastructure",
    related_company_ids: [],
    summary: "Pinecone introduced a serverless version of its vector database, reducing operational complexity for AI applications.",
  },
  {
    title: "Skild AI Raises $300M for Robot Foundation Models",
    url: "https://techcrunch.com/2024/05/23/skild-funding",
    published_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "Funding",
    related_company_ids: [],
    summary: "Skild AI secured $300 million in funding to develop foundation models for general-purpose robot intelligence.",
  },
  {
    title: "Fireworks AI Launches Optimized Inference Platform",
    url: "https://theverge.com/2024/05/22/fireworks-platform",
    published_at: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
    source: "The Verge",
    tag: "Infrastructure",
    related_company_ids: [],
    summary: "Fireworks AI launched a new inference platform optimized for running open-source AI models at scale.",
  },
  {
    title: "Abridge Receives FDA Clearance for AI Documentation",
    url: "https://fda.gov/2024/05/21/abridge-clearance",
    published_at: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
    source: "FDA News",
    tag: "Healthcare",
    related_company_ids: [],
    summary: "Abridge received FDA clearance for its AI-powered medical documentation system, marking a significant milestone for healthcare AI.",
  },
  {
    title: "Insitro Discovers New Drug Candidate Using AI",
    url: "https://nature.com/2024/05/20/insitro-drug",
    published_at: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Nature",
    tag: "Biotech",
    related_company_ids: [],
    summary: "Insitro announced the discovery of a new drug candidate using its AI-driven drug discovery platform.",
  },
  {
    title: "Helsing Secures European Defense Contract",
    url: "https://reuters.com/2024/05/19/helsing-contract",
    published_at: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Reuters",
    tag: "Defense",
    related_company_ids: [],
    summary: "European AI defense company Helsing secured a major contract to supply AI systems for military applications.",
  },
  {
    title: "Shield AI Deploys Autonomous Systems in Combat Zone",
    url: "https://defense.gov/2024/05/18/shield-deployment",
    published_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Defense News",
    tag: "Defense",
    related_company_ids: [],
    summary: "Shield AI deployed its autonomous AI systems in a combat zone for the first time, demonstrating real-world capabilities.",
  },
  {
    title: "Together AI Raises $130M for Open-Source Cloud",
    url: "https://techcrunch.com/2024/05/17/together-funding",
    published_at: new Date(Date.now() - 31 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "Funding",
    related_company_ids: [],
    summary: "Together AI secured $130 million in funding to expand its cloud platform for open-source AI models.",
  },
  {
    title: "Weights & Biases Launches Enterprise MLOps Suite",
    url: "https://zdnet.com/2024/05/16/wandb-enterprise",
    published_at: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
    source: "ZDNet",
    tag: "Enterprise",
    related_company_ids: [],
    summary: "Weights & Biases introduced an enterprise MLOps suite with enhanced security and collaboration features.",
  },
  {
    title: "Covariant Expands Robotics Platform to New Industries",
    url: "https://robotics.org/2024/05/15/covariant-expansion",
    published_at: new Date(Date.now() - 33 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Robotics Business Review",
    tag: "Robotics",
    related_company_ids: [],
    summary: "Covariant expanded its AI robotics platform to serve new industries beyond warehouse logistics.",
  },
  {
    title: "Sierra AI Raises $110M for Enterprise AI Agents",
    url: "https://venturebeat.com/2024/05/14/sierra-funding",
    published_at: new Date(Date.now() - 34 * 24 * 60 * 60 * 1000).toISOString(),
    source: "VentureBeat",
    tag: "Funding",
    related_company_ids: [],
    summary: "Sierra AI secured $110 million in funding to develop enterprise-focused AI agents for customer service.",
  },
  {
    title: "Adept AI Demonstrates Software Automation Capabilities",
    url: "https://wired.com/2024/05/13/adept-demo",
    published_at: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Wired",
    tag: "AI Agents",
    related_company_ids: [],
    summary: "Adept AI demonstrated its AI system's ability to automate complex software workflows across multiple applications.",
  },
  {
    title: "Inflection AI Launches Personal AI Assistant",
    url: "https://theverge.com/2024/05/12/inflection-assistant",
    published_at: new Date(Date.now() - 36 * 24 * 60 * 60 * 1000).toISOString(),
    source: "The Verge",
    tag: "Consumer",
    related_company_ids: [],
    summary: "Inflection AI launched a personal AI assistant with enhanced emotional intelligence and personalization features.",
  },
  {
    title: "Pika Labs Introduces Video-to-Video Generation",
    url: "https://arstechnica.com/2024/05/11/pika-video",
    published_at: new Date(Date.now() - 37 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Ars Technica",
    tag: "Video AI",
    related_company_ids: [],
    summary: "Pika Labs introduced video-to-video generation capabilities, allowing users to transform existing video content using AI.",
  },
  {
    title: "Luma AI Launches 3D Generation API",
    url: "https://techcrunch.com/2024/05/10/luma-api",
    published_at: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "3D AI",
    related_company_ids: [],
    summary: "Luma AI launched an API for its 3D content generation platform, enabling developers to integrate 3D AI into their applications.",
  },
  {
    title: "Poolside Raises $126M for AI Code Generation",
    url: "https://information.com/2024/05/09/poolside-funding",
    published_at: new Date(Date.now() - 39 * 24 * 60 * 60 * 1000).toISOString(),
    source: "The Information",
    tag: "Funding",
    related_company_ids: [],
    summary: "Poolside secured $126 million in funding to develop foundation models for software development and code generation.",
  },
  {
    title: "Modal Launches Serverless GPU Platform",
    url: "https://infoworld.com/2024/05/08/modal-gpu",
    published_at: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    source: "InfoWorld",
    tag: "Infrastructure",
    related_company_ids: [],
    summary: "Modal launched a serverless GPU platform for AI and ML workloads, simplifying cloud computing for developers.",
  },
  {
    title: "Notion AI Adds Advanced Writing Features",
    url: "https://theverge.com/2024/05/07/notion-ai-features",
    published_at: new Date(Date.now() - 41 * 24 * 60 * 60 * 1000).toISOString(),
    source: "The Verge",
    tag: "Productivity",
    related_company_ids: [],
    summary: "Notion AI added advanced writing features including style transfer, tone adjustment, and document summarization.",
  },
  {
    title: "Jasper AI Expands to Enterprise Market",
    url: "https://forbes.com/2024/05/06/jasper-enterprise",
    published_at: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Forbes",
    tag: "Enterprise",
    related_company_ids: [],
    summary: "Jasper AI expanded its AI content creation platform to serve enterprise customers with enhanced security and compliance.",
  },
  {
    title: "AI21 Labs Launches Jurassic-2 Models",
    url: "https://venturebeat.com/2024/05/05/ai21-jurassic",
    published_at: new Date(Date.now() - 43 * 24 * 60 * 60 * 1000).toISOString(),
    source: "VentureBeat",
    tag: "LLM",
    related_company_ids: [],
    summary: "AI21 Labs launched its Jurassic-2 family of large language models with improved performance and efficiency.",
  },
  {
    title: "Glean Raises $355M for Enterprise Search",
    url: "https://techcrunch.com/2024/05/04/glean-funding",
    published_at: new Date(Date.now() - 44 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "Funding",
    related_company_ids: [],
    summary: "Glean secured $355 million in funding to expand its AI-powered enterprise search platform.",
  },
  {
    title: "DataRobot Launches AI Governance Suite",
    url: "https://zdnet.com/2024/05/03/datarobot-governance",
    published_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    source: "ZDNet",
    tag: "Enterprise",
    related_company_ids: [],
    summary: "DataRobot launched a comprehensive AI governance suite to help enterprises manage their AI deployments.",
  },
  {
    title: "Dataiku Expands AI Platform Capabilities",
    url: "https://infoworld.com/2024/05/02/dataiku-platform",
    published_at: new Date(Date.now() - 46 * 24 * 60 * 60 * 1000).toISOString(),
    source: "InfoWorld",
    tag: "Enterprise",
    related_company_ids: [],
    summary: "Dataiku expanded its enterprise AI platform with new features for MLOps, data preparation, and model deployment.",
  },
  {
    title: "Descript Adds AI Voice Cloning",
    url: "https://theverge.com/2024/05/01/descript-voice",
    published_at: new Date(Date.now() - 47 * 24 * 60 * 60 * 1000).toISOString(),
    source: "The Verge",
    tag: "Audio AI",
    related_company_ids: [],
    summary: "Descript added AI voice cloning capabilities to its video and audio editing platform.",
  },
  {
    title: "AssemblyAI Launches Real-Time Transcription",
    url: "https://techcrunch.com/2024/04/30/assemblyai-realtime",
    published_at: new Date(Date.now() - 48 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "Audio AI",
    related_company_ids: [],
    summary: "AssemblyAI launched real-time speech recognition API for live transcription applications.",
  },
  {
    title: "Deepgram Expands Language Support",
    url: "https://venturebeat.com/2024/04/29/deepgram-languages",
    published_at: new Date(Date.now() - 49 * 24 * 60 * 60 * 1000).toISOString(),
    source: "VentureBeat",
    tag: "Audio AI",
    related_company_ids: [],
    summary: "Deepgram expanded its speech recognition platform to support 50+ languages with improved accuracy.",
  },
  {
    title: "Zipline Expands Drone Delivery Network",
    url: "https://reuters.com/2024/04/28/zipline-expansion",
    published_at: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Reuters",
    tag: "Robotics",
    related_company_ids: [],
    summary: "Zipline expanded its autonomous drone delivery network to serve new regions and healthcare facilities.",
  },
  {
    title: "Waabi Demonstrates Autonomous Trucking",
    url: "https://techcrunch.com/2024/04/27/waabi-trucking",
    published_at: new Date(Date.now() - 51 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "Robotics",
    related_company_ids: [],
    summary: "Waabi demonstrated its AI-first autonomous trucking technology in real-world highway conditions.",
  },
  {
    title: "SambaNova Launches New AI Hardware",
    url: "https://anandtech.com/2024/04/26/sambanova-hardware",
    published_at: new Date(Date.now() - 52 * 24 * 60 * 60 * 1000).toISOString(),
    source: "AnandTech",
    tag: "Hardware",
    related_company_ids: [],
    summary: "SambaNova launched new AI hardware optimized for training and running large language models.",
  },
  {
    title: "Cerebras Unveils Larger AI Chip",
    url: "https://ieee.org/2024/04/25/cerebras-chip",
    published_at: new Date(Date.now() - 53 * 24 * 60 * 60 * 1000).toISOString(),
    source: "IEEE Spectrum",
    tag: "Hardware",
    related_company_ids: [],
    summary: "Cerebras unveiled an even larger AI chip with improved performance for deep learning workloads.",
  },
  {
    title: "Vercel Launches AI-Powered Edge Functions",
    url: "https://theverge.com/2024/04/24/vercel-ai",
    published_at: new Date(Date.now() - 54 * 24 * 60 * 60 * 1000).toISOString(),
    source: "The Verge",
    tag: "Infrastructure",
    related_company_ids: [],
    summary: "Vercel launched AI-powered edge functions that enable developers to deploy AI models at the edge.",
  },
  {
    title: "Replicate Expands Model Library",
    url: "https://techcrunch.com/2024/04/23/replicate-library",
    published_at: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "Infrastructure",
    related_company_ids: [],
    summary: "Replicate expanded its community library of ML models with hundreds of new models for various AI tasks.",
  },
  {
    title: "Midjourney Launches Web Interface",
    url: "https://theverge.com/2024/04/22/midjourney-web",
    published_at: new Date(Date.now() - 56 * 24 * 60 * 60 * 1000).toISOString(),
    source: "The Verge",
    tag: "Image AI",
    related_company_ids: [],
    summary: "Midjourney launched a web interface for its AI image generation platform, improving accessibility for new users.",
  },
  {
    title: "Synthesia Adds Real-Time Avatar Generation",
    url: "https://wired.com/2024/04/21/synthesia-realtime",
    published_at: new Date(Date.now() - 57 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Wired",
    tag: "Video AI",
    related_company_ids: [],
    summary: "Synthesia added real-time AI avatar generation capabilities to its video synthesis platform.",
  },
  {
    title: "Cohere Launches Enterprise LLM Platform",
    url: "https://reuters.com/2024/04/20/cohere-enterprise",
    published_at: new Date(Date.now() - 58 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Reuters",
    tag: "Enterprise",
    related_company_ids: [],
    summary: "Cohere launched an enterprise-focused LLM platform with enhanced data privacy and security features.",
  },
  {
    title: "Google DeepMind Achieves Protein Folding Breakthrough",
    url: "https://nature.com/2024/04/19/deepmind-protein",
    published_at: new Date(Date.now() - 59 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Nature",
    tag: "Research",
    related_company_ids: [],
    summary: "Google DeepMind achieved a breakthrough in protein folding with its AlphaFold 3 model.",
  },
  {
    title: "Character AI Launches Mobile App",
    url: "https://techcrunch.com/2024/04/18/character-mobile",
    published_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "Consumer",
    related_company_ids: [],
    summary: "Character AI launched a mobile app for its AI chatbot platform, expanding its reach to mobile users.",
  },
  {
    title: "Mistral AI Partners with Major Cloud Providers",
    url: "https://venturebeat.com/2024/04/17/mistral-cloud",
    published_at: new Date(Date.now() - 61 * 24 * 60 * 60 * 1000).toISOString(),
    source: "VentureBeat",
    tag: "Partnership",
    related_company_ids: [],
    summary: "Mistral AI announced partnerships with major cloud providers to distribute its open-weight models.",
  },
  {
    title: "Perplexity AI Adds Academic Search",
    url: "https://theverge.com/2024/04/16/perplexity-academic",
    published_at: new Date(Date.now() - 62 * 24 * 60 * 60 * 1000).toISOString(),
    source: "The Verge",
    tag: "Search",
    related_company_ids: [],
    summary: "Perplexity AI added academic search capabilities to its AI-powered answer engine.",
  },
  {
    title: "Runway ML Raises Additional Funding",
    url: "https://bloomberg.com/2024/04/15/runway-funding",
    published_at: new Date(Date.now() - 63 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Bloomberg",
    tag: "Funding",
    related_company_ids: [],
    summary: "Runway ML raised additional funding to expand its AI video generation platform.",
  },
  {
    title: "ElevenLabs Launches Voice Cloning API",
    url: "https://techcrunch.com/2024/04/14/elevenlabs-api",
    published_at: new Date(Date.now() - 64 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "Audio AI",
    related_company_ids: [],
    summary: "ElevenLabs launched a voice cloning API for developers to integrate synthetic voices into their applications.",
  },
  {
    title: "Figure AI Secures Additional Funding",
    url: "https://reuters.com/2024/04/13/figure-funding",
    published_at: new Date(Date.now() - 65 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Reuters",
    tag: "Funding",
    related_company_ids: [],
    summary: "Figure AI secured additional funding to accelerate development of its humanoid robots.",
  },
  {
    title: "Harvey AI Expands to International Markets",
    url: "https://law.com/2024/04/12/harvey-international",
    published_at: new Date(Date.now() - 66 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Law.com",
    tag: "Legal AI",
    related_company_ids: [],
    summary: "Harvey AI expanded its AI legal platform to international markets with support for multiple languages.",
  },
  {
    title: "HeyGen Partners with Marketing Agencies",
    url: "https://adweek.com/2024/04/11/heygen-partners",
    published_at: new Date(Date.now() - 67 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Adweek",
    tag: "Partnership",
    related_company_ids: [],
    summary: "HeyGen announced partnerships with major marketing agencies to distribute its AI video generation platform.",
  },
  {
    title: "LangChain Launches Enterprise Version",
    url: "https://infoworld.com/2024/04/10/langchain-enterprise",
    published_at: new Date(Date.now() - 68 * 24 * 60 * 60 * 1000).toISOString(),
    source: "InfoWorld",
    tag: "Enterprise",
    related_company_ids: [],
    summary: "LangChain launched an enterprise version of its LLM framework with enhanced security and support.",
  },
  {
    title: "Pinecone Expands to European Markets",
    url: "https://techcrunch.com/2024/04/09/pinecone-europe",
    published_at: new Date(Date.now() - 69 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "Expansion",
    related_company_ids: [],
    summary: "Pinecone expanded its vector database services to European markets with new data centers.",
  },
  {
    title: "Skild AI Demonstrates Robot Learning",
    url: "https://ieee.org/2024/04/08/skild-learning",
    published_at: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000).toISOString(),
    source: "IEEE Spectrum",
    tag: "Robotics",
    related_company_ids: [],
    summary: "Skild AI demonstrated its robot foundation models learning new tasks with minimal training data.",
  },
  {
    title: "Fireworks AI Adds Model Optimization",
    url: "https://venturebeat.com/2024/04/07/fireworks-optimization",
    published_at: new Date(Date.now() - 71 * 24 * 60 * 60 * 1000).toISOString(),
    source: "VentureBeat",
    tag: "Infrastructure",
    related_company_ids: [],
    summary: "Fireworks AI added automatic model optimization features to its inference platform.",
  },
  {
    title: "Abridge Partners with Hospital Systems",
    url: "https://healthcareit.com/2024/04/06/abridge-partners",
    published_at: new Date(Date.now() - 72 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Healthcare IT News",
    tag: "Healthcare",
    related_company_ids: [],
    summary: "Abridge announced partnerships with major hospital systems to deploy its AI medical documentation platform.",
  },
  {
    title: "Insitro Expands Drug Discovery Pipeline",
    url: "https://biopharma.com/2024/04/05/insitro-pipeline",
    published_at: new Date(Date.now() - 73 * 24 * 60 * 60 * 1000).toISOString(),
    source: "BioPharma Dive",
    tag: "Biotech",
    related_company_ids: [],
    summary: "Insitro expanded its drug discovery pipeline with new therapeutic candidates identified by its AI platform.",
  },
  {
    title: "Helsing Wins European Defense Award",
    url: "https://defense.gov/2024/04/04/helsing-award",
    published_at: new Date(Date.now() - 74 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Defense News",
    tag: "Defense",
    related_company_ids: [],
    summary: "Helsing received a major European defense award for its AI military decision-making systems.",
  },
  {
    title: "Shield AI Expands Product Line",
    url: "https://reuters.com/2024/04/03/shield-products",
    published_at: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Reuters",
    tag: "Defense",
    related_company_ids: [],
    summary: "Shield AI expanded its autonomous systems product line with new drone and ground vehicle offerings.",
  },
  {
    title: "Together AI Adds Model Fine-Tuning",
    url: "https://techcrunch.com/2024/04/02/together-finetuning",
    published_at: new Date(Date.now() - 76 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "Infrastructure",
    related_company_ids: [],
    summary: "Together AI added model fine-tuning capabilities to its cloud platform for open-source AI models.",
  },
  {
    title: "Weights & Biases Adds Model Monitoring",
    url: "https://zdnet.com/2024/04/01/wandb-monitoring",
    published_at: new Date(Date.now() - 77 * 24 * 60 * 60 * 1000).toISOString(),
    source: "ZDNet",
    tag: "Enterprise",
    related_company_ids: [],
    summary: "Weights & Biases added real-time model monitoring capabilities to its MLOps platform.",
  },
  {
    title: "Covariant Raises Additional Funding",
    url: "https://venturebeat.com/2024/03/31/covariant-funding",
    published_at: new Date(Date.now() - 78 * 24 * 60 * 60 * 1000).toISOString(),
    source: "VentureBeat",
    tag: "Funding",
    related_company_ids: [],
    summary: "Covariant raised additional funding to expand its AI robotics platform for warehouse automation.",
  },
  {
    title: "Sierra AI Launches Beta Program",
    url: "https://theverge.com/2024/03/30/sierra-beta",
    published_at: new Date(Date.now() - 79 * 24 * 60 * 60 * 1000).toISOString(),
    source: "The Verge",
    tag: "Enterprise",
    related_company_ids: [],
    summary: "Sierra AI launched a beta program for its enterprise AI agents platform with select customers.",
  },
  {
    title: "Adept AI Demonstrates Web Automation",
    url: "https://wired.com/2024/03/29/adept-web",
    published_at: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Wired",
    tag: "AI Agents",
    related_company_ids: [],
    summary: "Adept AI demonstrated its AI system automating complex web-based workflows across multiple websites.",
  },
  {
    title: "Inflection AI Adds Voice Interface",
    url: "https://techcrunch.com/2024/03/28/inflection-voice",
    published_at: new Date(Date.now() - 81 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "Consumer",
    related_company_ids: [],
    summary: "Inflection AI added a voice interface to its personal AI assistant with natural conversation capabilities.",
  },
  {
    title: "Pika Labs Improves Video Quality",
    url: "https://arstechnica.com/2024/03/27/pika-quality",
    published_at: new Date(Date.now() - 82 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Ars Technica",
    tag: "Video AI",
    related_company_ids: [],
    summary: "Pika Labs significantly improved the quality and consistency of its AI video generation platform.",
  },
  {
    title: "Luma AI Adds Real-Time 3D Capture",
    url: "https://theverge.com/2024/03/26/luma-capture",
    published_at: new Date(Date.now() - 83 * 24 * 60 * 60 * 1000).toISOString(),
    source: "The Verge",
    tag: "3D AI",
    related_company_ids: [],
    summary: "Luma AI added real-time 3D capture capabilities using smartphone cameras.",
  },
  {
    title: "Poolside Adds Code Review Features",
    url: "https://information.com/2024/03/25/poolside-review",
    published_at: new Date(Date.now() - 84 * 24 * 60 * 60 * 1000).toISOString(),
    source: "The Information",
    tag: "Code AI",
    related_company_ids: [],
    summary: "Poolside added automated code review features to its AI code generation platform.",
  },
  {
    title: "Modal Expands GPU Options",
    url: "https://infoworld.com/2024/03/24/modal-gpu",
    published_at: new Date(Date.now() - 85 * 24 * 60 * 60 * 1000).toISOString(),
    source: "InfoWorld",
    tag: "Infrastructure",
    related_company_ids: [],
    summary: "Modal expanded its serverless GPU platform with additional GPU options and improved pricing.",
  },
  {
    title: "Notion AI Adds Team Collaboration",
    url: "https://techcrunch.com/2024/03/23/notion-team",
    published_at: new Date(Date.now() - 86 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "Productivity",
    related_company_ids: [],
    summary: "Notion AI added team collaboration features to its AI-powered workspace platform.",
  },
  {
    title: "Jasper AI Adds Brand Voice",
    url: "https://forbes.com/2024/03/22/jasper-brand",
    published_at: new Date(Date.now() - 87 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Forbes",
    tag: "Enterprise",
    related_company_ids: [],
    summary: "Jasper AI added brand voice customization to maintain consistent tone across AI-generated content.",
  },
  {
    title: "AI21 Labs Launches API Platform",
    url: "https://venturebeat.com/2024/03/21/ai21-api",
    published_at: new Date(Date.now() - 88 * 24 * 60 * 60 * 1000).toISOString(),
    source: "VentureBeat",
    tag: "LLM",
    related_company_ids: [],
    summary: "AI21 Labs launched an API platform for its Jurassic-2 large language models.",
  },
  {
    title: "Glean Adds Security Features",
    url: "https://zdnet.com/2024/03/20/glean-security",
    published_at: new Date(Date.now() - 89 * 24 * 60 * 60 * 1000).toISOString(),
    source: "ZDNet",
    tag: "Enterprise",
    related_company_ids: [],
    summary: "Glean added enhanced security features to its AI-powered enterprise search platform.",
  },
  {
    title: "DataRobot Adds AutoML Features",
    url: "https://infoworld.com/2024/03/19/datarobot-automl",
    published_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    source: "InfoWorld",
    tag: "Enterprise",
    related_company_ids: [],
    summary: "DataRobot added advanced AutoML features to its automated machine learning platform.",
  },
  {
    title: "Dataiku Adds Data Quality Tools",
    url: "https://techcrunch.com/2024/03/18/dataiku-quality",
    published_at: new Date(Date.now() - 91 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "Enterprise",
    related_company_ids: [],
    summary: "Dataiku added data quality assessment and improvement tools to its enterprise AI platform.",
  },
  {
    title: "Descript Adds Multi-Track Editing",
    url: "https://theverge.com/2024/03/17/descript-multitrack",
    published_at: new Date(Date.now() - 92 * 24 * 60 * 60 * 1000).toISOString(),
    source: "The Verge",
    tag: "Audio AI",
    related_company_ids: [],
    summary: "Descript added multi-track audio editing capabilities to its AI-powered editing platform.",
  },
  {
    title: "AssemblyAI Adds Speaker Diarization",
    url: "https://venturebeat.com/2024/03/16/assembly-diarization",
    published_at: new Date(Date.now() - 93 * 24 * 60 * 60 * 1000).toISOString(),
    source: "VentureBeat",
    tag: "Audio AI",
    related_company_ids: [],
    summary: "AssemblyAI added speaker diarization capabilities to its speech recognition API.",
  },
  {
    title: "Deepgram Adds Noise Cancellation",
    url: "https://techcrunch.com/2024/03/15/deepgram-noise",
    published_at: new Date(Date.now() - 94 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "Audio AI",
    related_company_ids: [],
    summary: "Deepgram added advanced noise cancellation to improve speech recognition accuracy in noisy environments.",
  },
  {
    title: "Zipline Expands to New Countries",
    url: "https://reuters.com/2024/03/14/zipline-countries",
    published_at: new Date(Date.now() - 95 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Reuters",
    tag: "Robotics",
    related_company_ids: [],
    summary: "Zipline expanded its drone delivery operations to additional countries in Africa and Asia.",
  },
  {
    title: "Waabi Raises Additional Funding",
    url: "https://bloomberg.com/2024/03/13/waabi-funding",
    published_at: new Date(Date.now() - 96 * 24 * 60 * 60 * 1000).toISOString(),
    source: "Bloomberg",
    tag: "Funding",
    related_company_ids: [],
    summary: "Waabi raised additional funding to advance its AI-first autonomous driving technology.",
  },
  {
    title: "SambaNova Partners with Cloud Providers",
    url: "https://anandtech.com/2024/03/12/sambanova-cloud",
    published_at: new Date(Date.now() - 97 * 24 * 60 * 60 * 1000).toISOString(),
    source: "AnandTech",
    tag: "Partnership",
    related_company_ids: [],
    summary: "SambaNova announced partnerships with cloud providers to offer its AI hardware as a service.",
  },
  {
    title: "Cerebras Adds Training Optimization",
    url: "https://ieee.org/2024/03/11/cerebras-training",
    published_at: new Date(Date.now() - 98 * 24 * 60 * 60 * 1000).toISOString(),
    source: "IEEE Spectrum",
    tag: "Hardware",
    related_company_ids: [],
    summary: "Cerebras added training optimization features to improve efficiency when training large AI models.",
  },
  {
    title: "Vercel Adds AI Model Marketplace",
    url: "https://theverge.com/2024/03/10/vercel-marketplace",
    published_at: new Date(Date.now() - 99 * 24 * 60 * 60 * 1000).toISOString(),
    source: "The Verge",
    tag: "Infrastructure",
    related_company_ids: [],
    summary: "Vercel added an AI model marketplace to its platform, allowing developers to easily deploy pre-trained models.",
  },
  {
    title: "Replicate Adds Model Versioning",
    url: "https://techcrunch.com/2024/03/09/replicate-versioning",
    published_at: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
    source: "TechCrunch",
    tag: "Infrastructure",
    related_company_ids: [],
    summary: "Replicate added model versioning and rollback capabilities to its ML model deployment platform.",
  },
];
