import { Company, Investor, Product, FundingRound, Founder, NewsArticle } from "@/types";

export const companies: Company[] = [
  { id: "1", name: "OpenAI", slug: "openai", logo_url: "/logos/openai.svg", description: "AI research and deployment company creating advanced language models including GPT-4, DALL-E, and ChatGPT.", category: "Large Language Models", stage: "Late Stage", hq_city: "San Francisco", hq_country: "USA", website: "https://openai.com", founded_year: 2015, employee_count: 4500, funding_total: 13000000000, is_unicorn: true, valuation: 80000000000, growth_score: 98, data_confidence_score: 99 },
  { id: "2", name: "Anthropic", slug: "anthropic", logo_url: "/logos/anthropic.svg", description: "AI safety company building reliable and steerable AI systems with the Claude language model.", category: "Large Language Models", stage: "Growth", hq_city: "San Francisco", hq_country: "USA", website: "https://anthropic.com", founded_year: 2021, employee_count: 1200, funding_total: 7500000000, is_unicorn: true, valuation: 18000000000, growth_score: 95, data_confidence_score: 95 },
  { id: "3", name: "Google DeepMind", slug: "google-deepmind", logo_url: "/logos/google-deepmind.svg", description: "AI research laboratory developing general-purpose AI technologies.", category: "AI Research", stage: "Late Stage", hq_city: "London", hq_country: "UK", website: "https://deepmind.com", founded_year: 2010, employee_count: 2500, funding_total: 5000000000, is_unicorn: true, valuation: 50000000000, growth_score: 92, data_confidence_score: 98 },
  { id: "4", name: "Hugging Face", slug: "hugging-face", logo_url: "/logos/huggingface.svg", description: "AI community platform and model hub for machine learning models.", category: "AI Infrastructure", stage: "Growth", hq_city: "New York", hq_country: "USA", website: "https://huggingface.co", founded_year: 2016, employee_count: 500, funding_total: 395000000, is_unicorn: true, valuation: 4500000000, growth_score: 90, data_confidence_score: 94 },
  { id: "5", name: "Midjourney", slug: "midjourney", logo_url: "/logos/midjourney.svg", description: "AI art and image generation platform for creative outputs.", category: "Image Generation", stage: "Growth", hq_city: "San Francisco", hq_country: "USA", website: "https://midjourney.com", founded_year: 2021, employee_count: 200, funding_total: 200000000, is_unicorn: true, valuation: 10000000000, growth_score: 88, data_confidence_score: 85 },
  { id: "6", name: "Stability AI", slug: "stability-ai", logo_url: "/logos/stability-ai.svg", description: "Open-source AI company behind Stable Diffusion.", category: "Image Generation", stage: "Growth", hq_city: "London", hq_country: "UK", website: "https://stability.ai", founded_year: 2020, employee_count: 300, funding_total: 101000000, is_unicorn: true, valuation: 1000000000, growth_score: 85, data_confidence_score: 80 },
  { id: "7", name: "Cohere", slug: "cohere", logo_url: "/logos/cohere.svg", description: "Enterprise AI platform providing LLMs for businesses.", category: "Large Language Models", stage: "Growth", hq_city: "Toronto", hq_country: "Canada", website: "https://cohere.com", founded_year: 2019, employee_count: 500, funding_total: 445000000, is_unicorn: true, valuation: 5500000000, growth_score: 87, data_confidence_score: 90 },
  { id: "8", name: "Perplexity AI", slug: "perplexity-ai", logo_url: "/logos/perplexity.svg", description: "AI-powered answer engine with real-time web search.", category: "AI Search", stage: "Growth", hq_city: "San Francisco", hq_country: "USA", website: "https://perplexity.ai", founded_year: 2022, employee_count: 150, funding_total: 165000000, is_unicorn: true, valuation: 1000000000, growth_score: 93, data_confidence_score: 88 },
  { id: "9", name: "Runway", slug: "runway", logo_url: "/logos/runway.svg", description: "AI video generation and editing platform.", category: "Video Generation", stage: "Growth", hq_city: "New York", hq_country: "USA", website: "https://runwayml.com", founded_year: 2018, employee_count: 250, funding_total: 237000000, is_unicorn: true, valuation: 1500000000, growth_score: 86, data_confidence_score: 85 },
  { id: "10", name: "Databricks", slug: "databricks", logo_url: "/logos/databricks.svg", description: "Data and AI platform on a lakehouse architecture.", category: "AI Infrastructure", stage: "Late Stage", hq_city: "San Francisco", hq_country: "USA", website: "https://databricks.com", founded_year: 2013, employee_count: 5000, funding_total: 3500000000, is_unicorn: true, valuation: 43000000000, growth_score: 91, data_confidence_score: 97 },
  { id: "11", name: "Scale AI", slug: "scale-ai", logo_url: "/logos/scale-ai.svg", description: "Data annotation and AI infrastructure platform.", category: "AI Infrastructure", stage: "Late Stage", hq_city: "San Francisco", hq_country: "USA", website: "https://scale.com", founded_year: 2016, employee_count: 1000, funding_total: 600000000, is_unicorn: true, valuation: 7300000000, growth_score: 88, data_confidence_score: 90 },
  { id: "12", name: "Mistral AI", slug: "mistral-ai", logo_url: "/logos/mistral-ai.svg", description: "French AI company building open-weight LLMs.", category: "Large Language Models", stage: "Growth", hq_city: "Paris", hq_country: "France", website: "https://mistral.ai", founded_year: 2023, employee_count: 100, funding_total: 640000000, is_unicorn: true, valuation: 6000000000, growth_score: 92, data_confidence_score: 85 },
  { id: "13", name: "Cursor", slug: "cursor", logo_url: "/logos/cursor.svg", description: "AI-first code editor for pair programming.", category: "Code Generation", stage: "Early Stage", hq_city: "San Francisco", hq_country: "USA", website: "https://cursor.sh", founded_year: 2022, employee_count: 50, funding_total: 60000000, is_unicorn: false, valuation: 400000000, growth_score: 96, data_confidence_score: 80 },
  { id: "14", name: "Cognition AI", slug: "cognition-ai", logo_url: "/logos/cognition-ai.svg", description: "Building Devin, the first AI software engineer.", category: "Code Generation", stage: "Early Stage", hq_city: "San Francisco", hq_country: "USA", website: "https://cognition.ai", founded_year: 2023, employee_count: 30, funding_total: 21000000, is_unicorn: false, valuation: 200000000, growth_score: 97, data_confidence_score: 70 },
  { id: "15", name: "ElevenLabs", slug: "elevenlabs", logo_url: "/logos/elevenlabs.svg", description: "AI voice synthesis platform.", category: "Audio Generation", stage: "Growth", hq_city: "New York", hq_country: "USA", website: "https://elevenlabs.io", founded_year: 2022, employee_count: 100, funding_total: 19000000, is_unicorn: false, valuation: 100000000, growth_score: 91, data_confidence_score: 82 },
  { id: "16", name: "Groq", slug: "groq", logo_url: "/logos/groq.svg", description: "Ultra-fast AI inference hardware.", category: "AI Infrastructure", stage: "Growth", hq_city: "Mountain View", hq_country: "USA", website: "https://groq.com", founded_year: 2016, employee_count: 200, funding_total: 367000000, is_unicorn: true, valuation: 1000000000, growth_score: 90, data_confidence_score: 82 },
  { id: "17", name: "Anduril", slug: "anduril", logo_url: "/logos/anduril.svg", description: "AI defense technology for autonomous systems.", category: "Defense AI", stage: "Late Stage", hq_city: "Irvine", hq_country: "USA", website: "https://anduril.com", founded_year: 2017, employee_count: 2000, funding_total: 2800000000, is_unicorn: true, valuation: 14000000000, growth_score: 90, data_confidence_score: 88 },
  { id: "18", name: "Figure AI", slug: "figure-ai", logo_url: "/logos/figure-ai.svg", description: "General-purpose humanoid robots.", category: "Robotics AI", stage: "Growth", hq_city: "Sunnyvale", hq_country: "USA", website: "https://figure.ai", founded_year: 2022, employee_count: 100, funding_total: 754000000, is_unicorn: true, valuation: 2600000000, growth_score: 94, data_confidence_score: 75 },
  { id: "19", name: "Suno AI", slug: "suno-ai", logo_url: "/logos/suno.svg", description: "AI music generation from text prompts.", category: "Audio Generation", stage: "Early Stage", hq_city: "Cambridge", hq_country: "USA", website: "https://suno.ai", founded_year: 2022, employee_count: 40, funding_total: 125000000, is_unicorn: false, valuation: 500000000, growth_score: 93, data_confidence_score: 75 },
  { id: "20", name: "LangChain", slug: "langchain", logo_url: "/logos/langchain.svg", description: "Framework for LLM-powered applications.", category: "AI Infrastructure", stage: "Early Stage", hq_city: "San Francisco", hq_country: "USA", website: "https://langchain.com", founded_year: 2022, employee_count: 60, funding_total: 35000000, is_unicorn: false, valuation: 200000000, growth_score: 92, data_confidence_score: 78 },
];

export const investors: Investor[] = [
  { id: "i1", name: "Sequoia Capital", slug: "sequoia-capital", type: "VC", bio: "One of the most prestigious venture capital firms in Silicon Valley, backing companies from seed to IPO.", aum: 85000000000, portfolio_count: 1500, stage_focus: ["Seed", "Early Stage", "Growth"], sector_focus: ["AI", "Enterprise", "Consumer", "Fintech", "Healthcare"], location: "Menlo Park, USA", logo_url: "/logos/sequoia-capital.svg", avg_check_size: 15000000, fund_number: 18 },
  { id: "i2", name: "Andreessen Horowitz", slug: "a16z", type: "VC", bio: "Leading venture capital firm investing in AI, crypto, bio, and enterprise software.", aum: 72000000000, portfolio_count: 1200, stage_focus: ["Seed", "Early Stage", "Growth", "Late Stage"], sector_focus: ["AI", "Crypto", "Bio", "Enterprise", "Consumer"], location: "Menlo Park, USA", logo_url: "/logos/a16z.svg", avg_check_size: 25000000, fund_number: 7 },
  { id: "i3", name: "Y Combinator", slug: "y-combinator", type: "VC", bio: "Startup accelerator that has funded over 4,000 companies including Airbnb, Stripe, and OpenAI.", aum: 30000000000, portfolio_count: 4000, stage_focus: ["Seed"], sector_focus: ["AI", "Enterprise", "Consumer", "Health", "Fintech"], location: "Mountain View, USA", logo_url: "/logos/y-combinator.svg", avg_check_size: 500000, fund_number: 30 },
  { id: "i4", name: "Tiger Global", slug: "tiger-global", type: "VC", bio: "Global investment firm focused on technology, growth equity, and public markets.", aum: 90000000000, portfolio_count: 600, stage_focus: ["Growth", "Late Stage"], sector_focus: ["AI", "Enterprise", "Consumer", "Fintech"], location: "New York, USA", logo_url: "/logos/tiger-global.svg", avg_check_size: 50000000, fund_number: 16 },
  { id: "i5", name: "Accel", slug: "accel", type: "VC", bio: "Global venture capital firm partnering with exceptional founders from seed to growth.", aum: 60000000000, portfolio_count: 800, stage_focus: ["Seed", "Early Stage", "Growth"], sector_focus: ["AI", "Enterprise", "Security", "Fintech"], location: "Palo Alto, USA", logo_url: "/logos/accel.svg", avg_check_size: 20000000, fund_number: 15 },
  { id: "i6", name: "Lightspeed Venture Partners", slug: "lightspeed", type: "VC", bio: "Global VC firm backing disruptive companies across enterprise, consumer, and AI.", aum: 25000000000, portfolio_count: 500, stage_focus: ["Early Stage", "Growth"], sector_focus: ["AI", "Enterprise", "Consumer", "Fintech"], location: "Menlo Park, USA", logo_url: "/logos/lightspeed.svg", avg_check_size: 15000000, fund_number: 12 },
  { id: "i7", name: "Index Ventures", slug: "index-ventures", type: "VC", bio: "Global VC investing in technology companies across stages and continents.", aum: 20000000000, portfolio_count: 600, stage_focus: ["Seed", "Early Stage", "Growth"], sector_focus: ["AI", "Enterprise", "Fintech", "Consumer"], location: "San Francisco, USA", logo_url: "/logos/index-ventures.svg", avg_check_size: 15000000, fund_number: 10 },
  { id: "i8", name: "Khosla Ventures", slug: "khosla-ventures", type: "VC", bio: "VC firm focused on deep tech, AI, climate, and healthcare investments.", aum: 15000000000, portfolio_count: 400, stage_focus: ["Seed", "Early Stage"], sector_focus: ["AI", "Climate", "Health", "Deep Tech"], location: "Menlo Park, USA", logo_url: "/logos/khosla-ventures.svg", avg_check_size: 10000000, fund_number: 8 },
  { id: "i9", name: "Greylock Partners", slug: "greylock", type: "VC", bio: "Early-stage VC firm backing founders building transformative enterprise and consumer companies.", aum: 10000000000, portfolio_count: 300, stage_focus: ["Seed", "Early Stage"], sector_focus: ["AI", "Enterprise", "Consumer", "Security"], location: "Menlo Park, USA", logo_url: "/logos/greylock.svg", avg_check_size: 12000000, fund_number: 16 },
  { id: "i10", name: "Elad Gil", slug: "elad-gil", type: "Angel", bio: "Angel investor and operator who has invested in over 200 companies including Stripe, Airbnb, and Figma.", aum: 2000000000, portfolio_count: 200, stage_focus: ["Seed", "Early Stage"], sector_focus: ["AI", "Enterprise", "Consumer", "Bio"], location: "San Francisco, USA", logo_url: "/logos/elad-gil.svg", avg_check_size: 1000000, fund_number: 1 },
  { id: "i11", name: "Nat Friedman", slug: "nat-friedman", type: "Angel", bio: "Former GitHub CEO turned angel investor backing AI and developer tool companies.", aum: 1000000000, portfolio_count: 100, stage_focus: ["Seed"], sector_focus: ["AI", "Developer Tools", "Open Source"], location: "San Francisco, USA", logo_url: "/logos/nat-friedman.svg", avg_check_size: 500000, fund_number: 1 },
  { id: "i12", name: "Microsoft", slug: "microsoft", type: "Corporate", bio: "Corporate venture arm investing in AI, cloud, and enterprise technology.", aum: 100000000000, portfolio_count: 200, stage_focus: ["Growth", "Late Stage"], sector_focus: ["AI", "Cloud", "Enterprise", "Developer Tools"], location: "Redmond, USA", logo_url: "/logos/microsoft.svg", avg_check_size: 100000000, fund_number: 1 },
  { id: "i13", name: "Google Ventures", slug: "google-ventures", type: "Corporate", bio: "Corporate venture capital arm of Alphabet investing in technology companies.", aum: 5000000000, portfolio_count: 500, stage_focus: ["Seed", "Early Stage", "Growth"], sector_focus: ["AI", "Enterprise", "Consumer", "Health"], location: "Mountain View, USA", logo_url: "/logos/google-ventures.svg", avg_check_size: 15000000, fund_number: 1 },
  { id: "i14", name: "OpenAI Startup Fund", slug: "openai-startup-fund", type: "Corporate", bio: "Corporate venture fund investing in AI companies building on OpenAI's platform.", aum: 1000000000, portfolio_count: 50, stage_focus: ["Seed", "Early Stage"], sector_focus: ["AI", "Enterprise", "Consumer"], location: "San Francisco, USA", logo_url: "/logos/openai-startup-fund.svg", avg_check_size: 5000000, fund_number: 1 },
  { id: "i15", name: "Sequoia Capital China", slug: "sequoia-china", type: "VC", bio: "Sequoia's China arm investing in technology companies across the region.", aum: 50000000000, portfolio_count: 800, stage_focus: ["Seed", "Early Stage", "Growth"], sector_focus: ["AI", "Enterprise", "Consumer", "Fintech"], location: "Beijing, China", logo_url: "/logos/sequoia-china.svg", avg_check_size: 20000000, fund_number: 12 },
  { id: "i16", name: "Benchmark", slug: "benchmark", type: "VC", bio: "Early-stage VC firm with a concentrated portfolio of iconic technology companies.", aum: 8000000000, portfolio_count: 100, stage_focus: ["Seed", "Early Stage"], sector_focus: ["AI", "Enterprise", "Consumer", "Marketplaces"], location: "San Francisco, USA", logo_url: "/logos/benchmark.svg", avg_check_size: 10000000, fund_number: 10 },
  { id: "i17", name: "General Catalyst", slug: "general-catalyst", type: "VC", bio: "VC firm investing in technology companies from seed to growth stage.", aum: 25000000000, portfolio_count: 500, stage_focus: ["Seed", "Early Stage", "Growth"], sector_focus: ["AI", "Enterprise", "Health", "Fintech"], location: "San Francisco, USA", logo_url: "/logos/general-catalyst.svg", avg_check_size: 20000000, fund_number: 12 },
  { id: "i18", name: "Founders Fund", slug: "founders-fund", type: "VC", bio: "VC firm investing in revolutionary technology companies across all stages.", aum: 12000000000, portfolio_count: 200, stage_focus: ["Seed", "Early Stage", "Growth"], sector_focus: ["AI", "Space", "Enterprise", "Consumer"], location: "San Francisco, USA", logo_url: "/logos/founders-fund.svg", avg_check_size: 15000000, fund_number: 7 },
  { id: "i19", name: "SoftBank Vision Fund", slug: "softbank-vision-fund", type: "Corporate", bio: "World's largest technology-focused investment fund backing AI and tech leaders.", aum: 100000000000, portfolio_count: 100, stage_focus: ["Growth", "Late Stage"], sector_focus: ["AI", "Enterprise", "Consumer", "Transportation"], location: "Tokyo, Japan", logo_url: "/logos/softbank.svg", avg_check_size: 200000000, fund_number: 2 },
  { id: "i20", name: "Insight Partners", slug: "insight-partners", type: "VC", bio: "Global VC firm investing in high-growth technology companies.", aum: 30000000000, portfolio_count: 400, stage_focus: ["Growth", "Late Stage"], sector_focus: ["AI", "Enterprise", "Security", "Data"], location: "New York, USA", logo_url: "/logos/insight-partners.svg", avg_check_size: 30000000, fund_number: 12 },
];

export const products: Product[] = [
  { id: "p1", company_id: "1", name: "ChatGPT", description: "Conversational AI assistant powered by GPT-4 for chat, coding, and creative tasks.", category: "Chat", launch_date: "2022-11-30", upvotes: 98500, website_url: "https://chat.openai.com", logo_url: "/logos/openai.svg" },
  { id: "p2", company_id: "1", name: "GPT-4", description: "Most advanced language model with multimodal capabilities.", category: "Code", launch_date: "2023-03-14", upvotes: 75000, website_url: "https://openai.com/gpt-4", logo_url: "/logos/openai.svg" },
  { id: "p3", company_id: "1", name: "DALL-E 3", description: "AI image generation from text descriptions with high fidelity.", category: "Image", launch_date: "2023-10-01", upvotes: 62000, website_url: "https://openai.com/dall-e-3", logo_url: "/logos/openai.svg" },
  { id: "p4", company_id: "2", name: "Claude 3", description: "Advanced AI assistant with focus on safety and helpfulness.", category: "Chat", launch_date: "2024-03-04", upvotes: 45000, website_url: "https://claude.ai", logo_url: "/logos/anthropic.svg" },
  { id: "p5", company_id: "2", name: "Claude API", description: "Enterprise API for integrating Claude's capabilities.", category: "Code", launch_date: "2023-07-01", upvotes: 28000, website_url: "https://anthropic.com/api", logo_url: "/logos/anthropic.svg" },
  { id: "p6", company_id: "5", name: "Midjourney v6", description: "Latest version of AI art generation with enhanced realism.", category: "Image", launch_date: "2023-12-15", upvotes: 55000, website_url: "https://midjourney.com", logo_url: "/logos/midjourney.svg" },
  { id: "p7", company_id: "6", name: "Stable Diffusion 3", description: "Open-source image generation model with improved quality.", category: "Image", launch_date: "2024-02-22", upvotes: 38000, website_url: "https://stability.ai", logo_url: "/logos/stability-ai.svg" },
  { id: "p8", company_id: "8", name: "Perplexity Pro", description: "AI search engine with real-time web answers and citations.", category: "Chat", launch_date: "2023-06-01", upvotes: 32000, website_url: "https://perplexity.ai", logo_url: "/logos/perplexity.svg" },
  { id: "p9", company_id: "9", name: "Runway Gen-3", description: "AI video generation model for professional content creation.", category: "Video", launch_date: "2024-01-15", upvotes: 29000, website_url: "https://runwayml.com", logo_url: "/logos/runway.svg" },
  { id: "p10", company_id: "12", name: "Mistral Large", description: "High-performance open-weight language model.", category: "Code", launch_date: "2024-02-26", upvotes: 25000, website_url: "https://mistral.ai", logo_url: "/logos/mistral-ai.svg" },
  { id: "p11", company_id: "13", name: "Cursor IDE", description: "AI-first code editor with intelligent pair programming.", category: "Code", launch_date: "2023-05-01", upvotes: 35000, website_url: "https://cursor.sh", logo_url: "/logos/cursor.svg" },
  { id: "p12", company_id: "14", name: "Devin", description: "Autonomous AI software engineer for completing software projects.", category: "Code", launch_date: "2024-03-12", upvotes: 42000, website_url: "https://cognition.ai", logo_url: "/logos/cognition-ai.svg" },
  { id: "p13", company_id: "15", name: "ElevenLabs Voice", description: "Natural-sounding AI voice synthesis in multiple languages.", category: "Audio", launch_date: "2023-01-15", upvotes: 31000, website_url: "https://elevenlabs.io", logo_url: "/logos/elevenlabs.svg" },
  { id: "p14", company_id: "19", name: "Suno v3", description: "AI music generation creating songs with lyrics and vocals.", category: "Audio", launch_date: "2024-02-01", upvotes: 27000, website_url: "https://suno.ai", logo_url: "/logos/suno.svg" },
  { id: "p15", company_id: "20", name: "LangChain Framework", description: "Framework for building LLM applications with chains and agents.", category: "Code", launch_date: "2022-10-01", upvotes: 22000, website_url: "https://langchain.com", logo_url: "/logos/langchain.svg" },
  { id: "p16", company_id: "1", name: "Sora", description: "AI video generation model creating realistic videos from text.", category: "Video", launch_date: "2024-02-15", upvotes: 48000, website_url: "https://openai.com/sora", logo_url: "/logos/openai.svg" },
  { id: "p17", company_id: "4", name: "Hugging Face Hub", description: "Platform for sharing and discovering ML models and datasets.", category: "Code", launch_date: "2020-01-01", upvotes: 18000, website_url: "https://huggingface.co", logo_url: "/logos/huggingface.svg" },
  { id: "p18", company_id: "16", name: "Groq LPU", description: "Ultra-fast inference engine for AI model deployment.", category: "Code", launch_date: "2023-11-01", upvotes: 15000, website_url: "https://groq.com", logo_url: "/logos/groq.svg" },
];

export const fundingRounds: FundingRound[] = [
  { id: "f1", company_id: "1", round_type: "Series A", amount: 1000000, currency: "USD", date: "2016-08-01", lead_investor_id: "i1", co_investors: ["i3"] },
  { id: "f2", company_id: "1", round_type: "Series B", amount: 100000000, currency: "USD", date: "2019-07-22", lead_investor_id: "i12", co_investors: ["i1", "i3"] },
  { id: "f3", company_id: "1", round_type: "Series C", amount: 10000000000, currency: "USD", date: "2023-01-23", lead_investor_id: "i12", co_investors: ["i1", "i2", "i4"] },
  { id: "f4", company_id: "2", round_type: "Series A", amount: 124000000, currency: "USD", date: "2022-04-01", lead_investor_id: "i1", co_investors: ["i2", "i10"] },
  { id: "f5", company_id: "2", round_type: "Series B", amount: 450000000, currency: "USD", date: "2023-05-01", lead_investor_id: "i2", co_investors: ["i1", "i4", "i12"] },
  { id: "f6", company_id: "2", round_type: "Series C", amount: 750000000, currency: "USD", date: "2024-03-01", lead_investor_id: "i2", co_investors: ["i1", "i4", "i12", "i19"] },
  { id: "f7", company_id: "4", round_type: "Series A", amount: 40000000, currency: "USD", date: "2021-05-01", lead_investor_id: "i1", co_investors: ["i2"] },
  { id: "f8", company_id: "4", round_type: "Series B", amount: 100000000, currency: "USD", date: "2022-05-01", lead_investor_id: "i2", co_investors: ["i1", "i5"] },
  { id: "f9", company_id: "4", round_type: "Series C", amount: 235000000, currency: "USD", date: "2023-08-01", lead_investor_id: "i1", co_investors: ["i2", "i5", "i7"] },
  { id: "f10", company_id: "7", round_type: "Series A", amount: 40000000, currency: "USD", date: "2021-02-01", lead_investor_id: "i1", co_investors: ["i2"] },
  { id: "f11", company_id: "7", round_type: "Series B", amount: 125000000, currency: "USD", date: "2022-06-01", lead_investor_id: "i4", co_investors: ["i1", "i2"] },
  { id: "f12", company_id: "7", round_type: "Series C", amount: 270000000, currency: "USD", date: "2023-07-01", lead_investor_id: "i2", co_investors: ["i1", "i4", "i7"] },
  { id: "f13", company_id: "8", round_type: "Seed", amount: 3000000, currency: "USD", date: "2022-09-01", lead_investor_id: "i3", co_investors: ["i10"] },
  { id: "f14", company_id: "8", round_type: "Series A", amount: 26000000, currency: "USD", date: "2023-03-01", lead_investor_id: "i2", co_investors: ["i3", "i10"] },
  { id: "f15", company_id: "8", round_type: "Series B", amount: 74000000, currency: "USD", date: "2024-01-01", lead_investor_id: "i2", co_investors: ["i4", "i7"] },
  { id: "f16", company_id: "12", round_type: "Seed", amount: 118000000, currency: "USD", date: "2023-06-01", lead_investor_id: "i6", co_investors: ["i7", "i8"] },
  { id: "f17", company_id: "12", round_type: "Series A", amount: 500000000, currency: "USD", date: "2023-12-01", lead_investor_id: "i2", co_investors: ["i6", "i7", "i12"] },
  { id: "f18", company_id: "18", round_type: "Series A", amount: 70000000, currency: "USD", date: "2023-05-01", lead_investor_id: "i8", co_investors: ["i18"] },
  { id: "f19", company_id: "18", round_type: "Series B", amount: 675000000, currency: "USD", date: "2024-02-01", lead_investor_id: "i2", co_investors: ["i8", "i12", "i19"] },
  { id: "f20", company_id: "10", round_type: "Series A", amount: 14000000, currency: "USD", date: "2014-01-01", lead_investor_id: "i2", co_investors: ["i1"] },
  { id: "f21", company_id: "10", round_type: "Series B", amount: 33000000, currency: "USD", date: "2015-06-01", lead_investor_id: "i1", co_investors: ["i2"] },
  { id: "f22", company_id: "10", round_type: "Series C", amount: 60000000, currency: "USD", date: "2016-12-01", lead_investor_id: "i2", co_investors: ["i1", "i4"] },
  { id: "f23", company_id: "10", round_type: "Series D", amount: 250000000, currency: "USD", date: "2018-02-01", lead_investor_id: "i2", co_investors: ["i1", "i4", "i5"] },
  { id: "f24", company_id: "10", round_type: "Series E", amount: 1000000000, currency: "USD", date: "2019-10-01", lead_investor_id: "i2", co_investors: ["i1", "i4", "i5", "i12"] },
  { id: "f25", company_id: "10", round_type: "Series F", amount: 1000000000, currency: "USD", date: "2021-08-01", lead_investor_id: "i2", co_investors: ["i1", "i4", "i5", "i12", "i19"] },
];

export const news: NewsArticle[] = [
  { id: "n1", title: "OpenAI Launches GPT-4o with Real-Time Voice and Vision", url: "https://example.com/openai-gpt4o", published_at: "2024-05-13T18:00:00Z", source: "TechCrunch", tag: "product-launch", related_company_ids: ["1"], summary: "OpenAI announced GPT-4o, a new flagship model that combines text, vision, and audio capabilities with real-time voice interaction." },
  { id: "n2", title: "Anthropic Raises $750M at $18.4B Valuation", url: "https://example.com/anthropic-funding", published_at: "2024-03-04T14:00:00Z", source: "Bloomberg", tag: "funding", related_company_ids: ["2"], summary: "Anthropic closed a $750 million funding round led by Andreessen Horowitz, bringing its valuation to $18.4 billion." },
  { id: "n3", title: "Mistral AI Partners with Microsoft for AI Distribution", url: "https://example.com/mistral-microsoft", published_at: "2024-02-26T10:00:00Z", source: "Reuters", tag: "partnership", related_company_ids: ["12"], summary: "French AI startup Mistral AI announced a multi-year partnership with Microsoft to distribute its models through Azure." },
  { id: "n4", title: "Cognition AI Unveils Devin, the First AI Software Engineer", url: "https://example.com/devin-launch", published_at: "2024-03-12T16:00:00Z", source: "The Verge", tag: "product-launch", related_company_ids: ["14"], summary: "Cognition AI introduced Devin, an autonomous AI agent capable of completing entire software engineering projects." },
  { id: "n5", title: "Figure AI Raises $675M from Microsoft, OpenAI, and Nvidia", url: "https://example.com/figure-funding", published_at: "2024-02-29T12:00:00Z", source: "Financial Times", tag: "funding", related_company_ids: ["18"], summary: "Humanoid robotics company Figure AI raised $675 million at a $2.6 billion valuation from a consortium of tech giants." },
  { id: "n6", title: "OpenAI's Sora Video Generation Model Wows Creators", url: "https://example.com/sora-video", published_at: "2024-02-15T20:00:00Z", source: "Wired", tag: "product-launch", related_company_ids: ["1"], summary: "OpenAI demonstrated Sora, a new AI model that generates realistic and imaginative videos from text descriptions." },
  { id: "n7", title: "Perplexity AI Hits 10M Monthly Active Users", url: "https://example.com/perplexity-growth", published_at: "2024-04-01T15:00:00Z", source: "TechCrunch", tag: "growth", related_company_ids: ["8"], summary: "AI search engine Perplexity AI announced it has reached 10 million monthly active users, doubling in three months." },
  { id: "n8", title: "Databricks Acquires AI Startup for $1.5B", url: "https://example.com/databricks-acquisition", published_at: "2024-05-01T09:00:00Z", source: "Bloomberg", tag: "acquisition", related_company_ids: ["10"], summary: "Databricks announced its largest acquisition to date, purchasing an AI infrastructure startup for $1.5 billion." },
  { id: "n9", title: "ElevenLabs Launches AI Voice Isolator Tool", url: "https://example.com/elevenlabs-voice", published_at: "2024-04-15T11:00:00Z", source: "The Verge", tag: "product-launch", related_company_ids: ["15"], summary: "ElevenLabs released a new AI-powered voice isolation tool that can separate and enhance individual voices in recordings." },
  { id: "n10", title: "Suno AI Raises $125M for AI Music Generation", url: "https://example.com/suno-funding", published_at: "2024-03-21T14:00:00Z", source: "TechCrunch", tag: "funding", related_company_ids: ["19"], summary: "AI music startup Suno raised $125 million to expand its text-to-music generation platform." },
  { id: "n11", title: "Anduril Wins $1B Defense Contract for AI Systems", url: "https://example.com/anduril-contract", published_at: "2024-04-20T08:00:00Z", source: "Reuters", tag: "contract", related_company_ids: ["17"], summary: "Defense tech company Anduril secured a $1 billion contract to supply AI-powered autonomous systems to the US military." },
  { id: "n12", title: "Groq Raises $640M to Challenge Nvidia in AI Inference", url: "https://example.com/groq-funding", published_at: "2024-04-10T16:00:00Z", source: "Financial Times", tag: "funding", related_company_ids: ["16"], summary: "AI chip startup Groq raised $640 million to scale its ultra-fast inference hardware for AI model deployment." },
  { id: "n13", title: "Hugging Face Releases Open-Source AI Assistant", url: "https://example.com/huggingface-assistant", published_at: "2024-05-05T10:00:00Z", source: "TechCrunch", tag: "product-launch", related_company_ids: ["4"], summary: "Hugging Face launched an open-source AI assistant platform, challenging proprietary alternatives." },
  { id: "n14", title: "Scale AI Secures $1B in New Funding for Data Infrastructure", url: "https://example.com/scale-funding", published_at: "2024-04-25T13:00:00Z", source: "Bloomberg", tag: "funding", related_company_ids: ["11"], summary: "Scale AI raised $1 billion to expand its data annotation and AI infrastructure platform for enterprise customers." },
  { id: "n15", title: "Cohere Launches Enterprise-Grade AI Security Platform", url: "https://example.com/cohere-security", published_at: "2024-05-10T09:00:00Z", source: "Wired", tag: "product-launch", related_company_ids: ["7"], summary: "Cohere released a new enterprise AI platform with enhanced security features for regulated industries." },
];

export const founders: Founder[] = [
  { id: "fo1", name: "Sam Altman", slug: "sam-altman", title: "CEO", company_id: "1", bio: "Co-founder and CEO of OpenAI, former president of Y Combinator.", twitter: "sama", linkedin: "samaltman", location: "San Francisco, USA", photo_url: "https://upload.wikimedia.org/wikipedia/commons/0/04/OpenAI_Logo.svg" },
  { id: "fo2", name: "Dario Amodei", slug: "dario-amodei", title: "CEO", company_id: "2", bio: "Co-founder and CEO of Anthropic, former VP of Research at OpenAI.", twitter: "darioamodei", linkedin: "darioamodei", location: "San Francisco, USA", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Anthropic_logo.svg/128px-Anthropic_logo.svg.png" },
  { id: "fo3", name: "Demis Hassabis", slug: "demis-hassabis", title: "CEO", company_id: "3", bio: "Co-founder and CEO of Google DeepMind, world-renowned AI researcher.", twitter: "demishassabis", linkedin: "demishassabis", location: "London, UK", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Google_DeepMind_logo.svg/128px-Google_DeepMind_logo.svg.png" },
  { id: "fo4", name: "Clement Delangue", slug: "clement-delangue", title: "CEO", company_id: "4", bio: "Co-founder and CEO of Hugging Face, building the open-source AI community.", twitter: "clementdelangue", linkedin: "clementdelangue", location: "New York, USA", photo_url: "https://huggingface.co/front/assets/huggingface-logo-noborder.svg" },
  { id: "fo5", name: "David Holz", slug: "david-holz", title: "CEO", company_id: "5", bio: "Founder and CEO of Midjourney, former Leap Motion CTO.", twitter: "davidholz", linkedin: "davidholz", location: "San Francisco, USA", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Midjourney_website_icon.svg/128px-Midjourney_website_icon.svg.png" },
  { id: "fo6", name: "Emad Mostaque", slug: "emad-mostaque", title: "CEO", company_id: "6", bio: "Founder and CEO of Stability AI, democratizing AI through open-source.", twitter: "emostaque", linkedin: "emadmostaque", location: "London, UK", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Stability_AI_logo.svg/128px-Stability_AI_logo.svg.png" },
  { id: "fo7", name: "Aidan Gomez", slug: "aidan-gomez", title: "CEO", company_id: "7", bio: "Co-founder and CEO of Cohere, co-author of the Transformer architecture.", twitter: "aidangomez", linkedin: "aidangomez", location: "Toronto, Canada", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Cohere_logo.svg/128px-Cohere_logo.svg.png" },
  { id: "fo8", name: "Aravind Srinivas", slug: "aravind-srinivas", title: "CEO", company_id: "8", bio: "Co-founder and CEO of Perplexity AI, former OpenAI researcher.", twitter: "aravindvs", linkedin: "aravindsrinivas", location: "San Francisco, USA", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Perplexity_AI_logo.svg/128px-Perplexity_AI_logo.svg.png" },
  { id: "fo9", name: "Cristobal Valenzuela", slug: "cristobal-valenzuela", title: "CEO", company_id: "9", bio: "Co-founder and CEO of Runway, pioneering AI video generation.", twitter: "cvalenzuela", linkedin: "cvalenzuela", location: "New York, USA", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Runway_logo.svg/128px-Runway_logo.svg.png" },
  { id: "fo10", name: "Ali Ghodsi", slug: "ali-ghodsi", title: "CEO", company_id: "10", bio: "Co-founder and CEO of Databricks, professor at UC Berkeley.", twitter: "alighodsi", linkedin: "alighodsi", location: "San Francisco, USA", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Databricks_logo.svg/128px-Databricks_logo.svg.png" },
  { id: "fo11", name: "Alexandr Wang", slug: "alexandr-wang", title: "CEO", company_id: "11", bio: "Founder and CEO of Scale AI, youngest self-made billionaire.", twitter: "alexandrwang", linkedin: "alexandrwang", location: "San Francisco, USA", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Scale_AI_logo.svg/128px-Scale_AI_logo.svg.png" },
  { id: "fo12", name: "Arthur Mensch", slug: "arthur-mensch", title: "CEO", company_id: "12", bio: "Co-founder and CEO of Mistral AI, former DeepMind researcher.", twitter: "arthurmensch", linkedin: "arthurmensch", location: "Paris, France", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Mistral_AI_logo.svg/128px-Mistral_AI_logo.svg.png" },
  { id: "fo13", name: "Aman Sanger", slug: "aman-sanger", title: "CEO", company_id: "13", bio: "Co-founder and CEO of Cursor, building AI-native development tools.", twitter: "amansanger", linkedin: "amansanger", location: "San Francisco, USA", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Cursor_logo.svg/128px-Cursor_logo.svg.png" },
  { id: "fo14", name: "Scott Wu", slug: "scott-wu", title: "CEO", company_id: "14", bio: "Co-founder and CEO of Cognition AI, creator of Devin.", twitter: "scottwu", linkedin: "scottwu", location: "San Francisco, USA", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Cognition_AI_logo.svg/128px-Cognition_AI_logo.svg.png" },
  { id: "fo15", name: "Piotr Krzysztof Kozak", slug: "piotr-kozak", title: "CEO", company_id: "15", bio: "Co-founder and CEO of ElevenLabs, pioneering AI voice technology.", twitter: "piotrkozak", linkedin: "piotrkozak", location: "New York, USA", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/ElevenLabs_logo.svg/128px-ElevenLabs_logo.svg.png" },
  { id: "fo16", name: "Jonathan Ross", slug: "jonathan-ross", title: "CEO", company_id: "16", bio: "Founder and CEO of Groq, former Google TPU engineer.", twitter: "jonathanross", linkedin: "jonathanross", location: "Mountain View, USA", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Groq_logo.svg/128px-Groq_logo.svg.png" },
  { id: "fo17", name: "Palmer Luckey", slug: "palmer-luckey", title: "CEO", company_id: "17", bio: "Founder and CEO of Anduril, founder of Oculus VR.", twitter: "palmerluckey", linkedin: "palmerluckey", location: "Irvine, USA", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Anduril_logo.svg/128px-Anduril_logo.svg.png" },
  { id: "fo18", name: "Brett Adcock", slug: "brett-adcock", title: "CEO", company_id: "18", bio: "Founder and CEO of Figure AI, founder of Archer Aviation.", twitter: "brettadcock", linkedin: "brettadcock", location: "Sunnyvale, USA", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Figure_AI_logo.svg/128px-Figure_AI_logo.svg.png" },
  { id: "fo19", name: "Mikey Shulman", slug: "mikey-shulman", title: "CEO", company_id: "19", bio: "Co-founder and CEO of Suno, building AI music generation.", twitter: "mikeyshulman", linkedin: "mikeyshulman", location: "Cambridge, USA", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Suno_AI_logo.svg/128px-Suno_AI_logo.svg.png" },
  { id: "fo20", name: "Harrison Chase", slug: "harrison-chase", title: "CEO", company_id: "20", bio: "Founder and CEO of LangChain, building LLM application framework.", twitter: "harrisonchase", linkedin: "harrisonchase", location: "San Francisco, USA", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/LangChain_logo.svg/128px-LangChain_logo.svg.png" },
];

export const getCompanyById = (id: string) => companies.find(c => c.id === id);
export const getCompanyBySlug = (slug: string) => companies.find(c => c.slug === slug);
export const getInvestorBySlug = (slug: string) => investors.find(i => i.slug === slug);
export const getProductsByCompany = (companyId: string) => products.filter(p => p.company_id === companyId);
export const getFundingByCompany = (companyId: string) => fundingRounds.filter(f => f.company_id === companyId);
export const getFoundersByCompany = (companyId: string) => founders.filter(f => f.company_id === companyId);
export const getNewsByCompany = (companyId: string) => news.filter(n => n.related_company_ids.includes(companyId));
export const getInvestorById = (id: string) => investors.find(i => i.id === id);
export const getCompanyInvestors = (companyId: string) => {
  const rounds = getFundingByCompany(companyId);
  const ids = new Set<string>();
  rounds.forEach(r => { ids.add(r.lead_investor_id); r.co_investors.forEach(ci => ids.add(ci)); });
  return Array.from(ids).map(id => getInvestorById(id)).filter(Boolean) as Investor[];
};
